begin;
create extension if not exists pgtap with schema extensions;
select plan(32);
select has_table('public','apostolic_vessel_catalog','vessel catalog exists');
select has_table('public','apostolic_city_fleet','city fleet exists');
select has_table('public','apostolic_vessel_queue','vessel queue exists');
select has_index('public','apostolic_vessel_queue','apostolic_vessel_one_active_idx','one vessel queue is active');
select has_index('public','apostolic_vessel_queue','apostolic_vessel_due_idx','due vessel jobs are indexed');
select has_trigger('public','apostolic_cities','apostolic_city_fleet_after_insert','new cities receive fleet rows');
select has_trigger('public','apostolic_training_queue','apostolic_training_research_guard','unit training enforces research');
select has_trigger('public','apostolic_building_action_queue','apostolic_purpose_research_guard','purposes enforce research');
select is((select count(*)::integer from public.apostolic_research_catalog where sort_order between 9 and 16),8,'eight researches added');
select is((select count(*)::integer from public.apostolic_vessel_catalog),4,'four vessel classes exist');
select is((select count(*)::integer from public.apostolic_vessel_catalog where role='merchant'),2,'two merchant vessels exist');
select is((select count(*)::integer from public.apostolic_vessel_catalog where role='defense'),2,'two defense vessels exist');
select is((select count(*)::integer from public.apostolic_vessel_catalog where costs?'gems'),0,'vessels never cost gems');
select is((select count(*)::integer from public.apostolic_research_catalog where sort_order between 9 and 16 and base_costs?'gems'),0,'research never costs gems');
select col_not_null('public','apostolic_unit_catalog','required_research_code','every unit requires research');
select is((select count(*)::integer from public.apostolic_unit_catalog where required_research_code is not null),4,'all units connect to research');
select is((select count(*)::integer from public.apostolic_building_action_catalog where required_research_code is not null),5,'advanced purposes require research');
select function_returns('public','apostolic_get_fleet_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_sync_fleet_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_start_vessel_construction',array['text','integer','uuid'],'jsonb');
select is((select prosecdef from pg_proc where oid='public.apostolic_get_fleet_center()'::regprocedure),true,'fleet center is server controlled');
select is((select prosecdef from pg_proc where oid='public.apostolic_start_vessel_construction(text,integer,uuid)'::regprocedure),true,'construction is server controlled');
select is((select proconfig@>array['search_path=""']from pg_proc where oid='public.apostolic_start_vessel_construction(text,integer,uuid)'::regprocedure),true,'construction has empty search path');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_start_vessel_construction'and grantee='anon'),0,'anonymous cannot construct vessels');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_start_vessel_construction'and grantee='authenticated'),1,'authenticated can construct vessels');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_vessel_catalog'::regclass),true,'vessel catalog forces RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_city_fleet'::regclass),true,'city fleet forces RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_vessel_queue'::regclass),true,'vessel queue forces RLS');
select is((select position('research required:'in pg_get_functiondef('public.apostolic_start_vessel_construction(text,integer,uuid)'::regprocedure))>0),true,'vessels verify research');
select is((select position('apostolic_training_queue'in pg_get_functiondef('public.apostolic_require_connected_research()'::regprocedure))>0),true,'guard covers units');
select is((select position('apostolic_building_action_catalog'in pg_get_functiondef('public.apostolic_require_connected_research()'::regprocedure))>0),true,'guard covers purposes');
select is((select count(*)::integer from public.apostolic_vessel_catalog where required_research_code is null),0,'all vessels require research');
select*from finish();
rollback;
