begin;
create extension if not exists pgtap with schema extensions;
select plan(34);
select has_table('public','apostolic_maritime_route_catalog','maritime route catalog exists');
select has_table('public','apostolic_maritime_voyages','maritime voyages exist');
select has_table('public','apostolic_maritime_reports','maritime reports exist');
select has_pk('public','apostolic_maritime_route_catalog','route catalog has primary key');
select has_pk('public','apostolic_maritime_voyages','voyages have primary key');
select has_pk('public','apostolic_maritime_reports','reports have primary key');
select has_index('public','apostolic_maritime_voyages','apostolic_maritime_one_active_idx','only one convoy sails per city');
select has_index('public','apostolic_maritime_voyages','apostolic_maritime_due_idx','due voyages are indexed');
select has_index('public','apostolic_maritime_voyages','apostolic_maritime_history_idx','voyage history is indexed');
select has_index('public','apostolic_maritime_reports','apostolic_maritime_reports_owner_idx','report history is indexed');
select is((select count(*)::integer from public.apostolic_maritime_route_catalog),4,'four original routes exist');
select is((select count(*)::integer from public.apostolic_maritime_route_catalog where required_research_code is null),0,'every route requires research');
select is((select count(*)::integer from public.apostolic_maritime_route_catalog where duration_seconds<300),0,'routes preserve long progression');
select is((select count(*)::integer from information_schema.columns where table_schema='public'and table_name in('apostolic_maritime_route_catalog','apostolic_maritime_voyages','apostolic_maritime_reports')and column_name in('gems','premium','speed_boost')),0,'maritime play has no premium advantage');
select col_not_null('public','apostolic_maritime_voyages','cargo_capacity','voyage records cargo capacity');
select col_not_null('public','apostolic_maritime_voyages','escort_power','voyage records escort power');
select col_not_null('public','apostolic_maritime_voyages','idempotency_key','voyage requires idempotency');
select function_returns('public','apostolic_get_maritime_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_sync_maritime_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_start_maritime_voyage',array['text','text','integer','text','integer','text','integer','uuid'],'jsonb');
select is((select prosecdef from pg_proc where oid='public.apostolic_get_maritime_center()'::regprocedure),true,'maritime center is server controlled');
select is((select prosecdef from pg_proc where oid='public.apostolic_sync_maritime_center()'::regprocedure),true,'voyage settlement is server controlled');
select is((select prosecdef from pg_proc where oid='public.apostolic_start_maritime_voyage(text,text,integer,text,integer,text,integer,uuid)'::regprocedure),true,'departure is server controlled');
select is((select proconfig@>array['search_path=""']from pg_proc where oid='public.apostolic_start_maritime_voyage(text,text,integer,text,integer,text,integer,uuid)'::regprocedure),true,'departure has empty search path');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_start_maritime_voyage'and grantee='anon'),0,'anonymous cannot start voyages');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_start_maritime_voyage'and grantee='authenticated'),1,'authenticated can start voyages');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_maritime_route_catalog'::regclass),true,'routes force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_maritime_voyages'::regclass),true,'voyages force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_maritime_reports'::regclass),true,'reports force RLS');
select is((select position('cargo capacity exceeded'in pg_get_functiondef('public.apostolic_start_maritime_voyage(text,text,integer,text,integer,text,integer,uuid)'::regprocedure))>0),true,'departure enforces cargo capacity');
select is((select position('daily voyage limit reached'in pg_get_functiondef('public.apostolic_start_maritime_voyage(text,text,integer,text,integer,text,integer,uuid)'::regprocedure))>0),true,'departure enforces daily antiabuse limit');
select is((select position('role=''defense'''in pg_get_functiondef('public.apostolic_start_maritime_voyage(text,text,integer,text,integer,text,integer,uuid)'::regprocedure))>0),true,'escort must be defensive');
select is((select position('risk_percent-least'in pg_get_functiondef('public.apostolic_sync_maritime_center()'::regprocedure))>0),true,'escort reduces voyage risk');
select is((select position('maritime_trade:'in pg_get_functiondef('public.apostolic_sync_maritime_center()'::regprocedure))>0),true,'trade reward is audited in ledger');
select*from finish();
rollback;
