begin;
create extension if not exists pgtap with schema extensions;
select plan(40);
select has_table('public','apostolic_island_catalog','island catalog exists');
select has_table('public','apostolic_island_discoveries','island discoveries exist');
select has_table('public','apostolic_colonization_projects','colonization projects exist');
select has_table('public','apostolic_colonies','colonies exist');
select has_table('public','apostolic_colony_resources','colony resources exist');
select has_table('public','apostolic_colony_log','colony audit log exists');
select has_pk('public','apostolic_island_catalog','islands have primary key');
select has_pk('public','apostolic_colonies','colonies have primary key');
select has_pk('public','apostolic_colony_resources','colony resources have primary key');
select has_index('public','apostolic_colonization_projects','apostolic_colonization_one_active_idx','one expedition is active');
select has_index('public','apostolic_colonization_projects','apostolic_colonization_due_idx','due expeditions are indexed');
select has_index('public','apostolic_colonies','apostolic_colonies_owner_idx','owner colonies are indexed');
select has_index('public','apostolic_colony_log','apostolic_colony_log_owner_idx','colony history is indexed');
select is((select count(*)::integer from public.apostolic_island_catalog),6,'six original islands exist');
select is((select count(*)::integer from public.apostolic_island_catalog where required_research_code is null),0,'all islands require research');
select is((select count(*)::integer from public.apostolic_island_catalog where exploration_costs?'gems'or foundation_costs?'gems'),0,'colonization never costs gems');
select is((select count(*)::integer from public.apostolic_island_catalog where foundation_seconds<14400),0,'founding preserves long progression');
select col_not_null('public','apostolic_colonization_projects','idempotency_key','expeditions require idempotency');
select col_not_null('public','apostolic_colonies','corruption','colonies track corruption');
select col_not_null('public','apostolic_colonies','focus','colonies track administrative focus');
select function_returns('public','apostolic_get_colonization_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_sync_colonization_center',array[]::text[],'jsonb');
select function_returns('public','apostolic_start_island_exploration',array['text','text','uuid'],'jsonb');
select function_returns('public','apostolic_found_colony',array['text','text','text','text','integer','uuid'],'jsonb');
select function_returns('public','apostolic_set_colony_focus',array['uuid','text','uuid'],'jsonb');
select is((select prosecdef from pg_proc where oid='public.apostolic_start_island_exploration(text,text,uuid)'::regprocedure),true,'exploration is server controlled');
select is((select prosecdef from pg_proc where oid='public.apostolic_found_colony(text,text,text,text,integer,uuid)'::regprocedure),true,'foundation is server controlled');
select is((select proconfig@>array['search_path=""']from pg_proc where oid='public.apostolic_found_colony(text,text,text,text,integer,uuid)'::regprocedure),true,'foundation has empty search path');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_found_colony'and grantee='anon'),0,'anonymous cannot found colonies');
select is((select count(*)::integer from information_schema.routine_privileges where routine_schema='public'and routine_name='apostolic_found_colony'and grantee='authenticated'),1,'authenticated can found colonies');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_island_catalog'::regclass),true,'islands force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_island_discoveries'::regclass),true,'discoveries force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_colonization_projects'::regclass),true,'projects force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_colonies'::regclass),true,'colonies force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_colony_resources'::regclass),true,'colony resources force RLS');
select is((select relrowsecurity and relforcerowsecurity from pg_class where oid='public.apostolic_colony_log'::regclass),true,'colony log forces RLS');
select is((select position('exploration limit reached'in pg_get_functiondef('public.apostolic_start_island_exploration(text,text,uuid)'::regprocedure))>0),true,'exploration has antiabuse limit');
select is((select position('colony limit reached'in pg_get_functiondef('public.apostolic_found_colony(text,text,text,text,integer,uuid)'::regprocedure))>0),true,'foundation enforces progressive limit');
select is((select position('foundation cargo capacity exceeded'in pg_get_functiondef('public.apostolic_found_colony(text,text,text,text,integer,uuid)'::regprocedure))>0),true,'foundation enforces fleet capacity');
select is((select position('interval''6 hours'''in pg_get_functiondef('public.apostolic_set_colony_focus(uuid,text,uuid)'::regprocedure))>0),true,'focus changes have cooldown');
select*from finish();
rollback;
