export type ArenaCatalogCard = {
  id: number; slug: string; name: string; rarity: "common" | "rare" | "epic" | "legendary" | "champion";
  faith: number; type: string; hp: string; damage: string; dps: string; range: string; speed: string;
  description: string; portrait: string;
};

const commonArt = (id: number, slug: string) => `/games/apostolic-arena/cards/art/common/${String(id).padStart(3, "0")}-${slug}-v1.webp`;

export const ARENA_CARD_CATALOG: ArenaCatalogCard[] = [
  { id:1, slug:"davi-e-a-funda", name:"Davi e a Funda", rarity:"common", faith:2, type:"Tropa terrestre", hp:"320", damage:"90", dps:"75", range:"5,5 tiles", speed:"Rápida", description:"Jovem pastor corajoso que ataca à distância com sua funda de precisão.", portrait:commonArt(1,"davi-e-a-funda") },
  { id:2, slug:"soldados-de-israel", name:"Soldados de Israel", rarity:"common", faith:3, type:"Horda (4)", hp:"150 ×4", damage:"65", dps:"65", range:"Corpo a corpo", speed:"Média", description:"Esquadrão leal com lanças e escudos para contenção estratégica.", portrait:commonArt(2,"soldados-de-israel") },
  { id:3, slug:"pomba-da-paz", name:"Pomba da Paz", rarity:"common", faith:1, type:"Tropa aérea", hp:"90", damage:"35", dps:"40", range:"3,5 tiles", speed:"Muito rápida", description:"Unidade voadora de ciclo rápido para distração e patrulha.", portrait:commonArt(3,"pomba-da-paz") },
  { id:4, slug:"bando-de-pombas", name:"Bando de Pombas", rarity:"common", faith:2, type:"Horda aérea (4)", hp:"80 ×4", damage:"30", dps:"35", range:"3 tiles", speed:"Muito rápida", description:"Grupo aéreo de ciclo rápido para distrair tropas de distância.", portrait:commonArt(4,"bando-de-pombas") },
  { id:5, slug:"arqueiros-de-juda", name:"Arqueiros de Judá", rarity:"common", faith:3, type:"Tropa (2)", hp:"210 ×2", damage:"85", dps:"70", range:"5 tiles", speed:"Média", description:"Dupla de atiradores para suporte defensivo terrestre e aéreo.", portrait:commonArt(5,"arqueiros-de-juda") },
  { id:6, slug:"bando-de-ovelhas", name:"Bando de Ovelhas", rarity:"common", faith:2, type:"Horda (6)", hp:"60 ×6", damage:"20", dps:"25", range:"Corpo a corpo", speed:"Rápida", description:"Grupo frágil e numeroso que ajuda a conter ataques pesados.", portrait:commonArt(6,"bando-de-ovelhas") },
  { id:7, slug:"guardas-de-jerusalem", name:"Guardas de Jerusalém", rarity:"common", faith:3, type:"Tropa (2)", hp:"300 ×2", damage:"95", dps:"80", range:"Corpo a corpo longo", speed:"Média", description:"Lanceiros de elite com escudos e estocada longa.", portrait:commonArt(7,"guardas-de-jerusalem") },
  { id:8, slug:"codornizes-do-deserto", name:"Codornizes do Deserto", rarity:"common", faith:2, type:"Aérea / Suporte", hp:"110", damage:"25", dps:"20", range:"Corpo a corpo", speed:"Rápida", description:"Ao serem derrotadas, deixam suprimento restaurador para aliados.", portrait:commonArt(8,"codornizes-do-deserto") },
  { id:9, slug:"fundibularios-de-benjamim", name:"Fundibulários de Benjamim", rarity:"common", faith:3, type:"Tropa (2)", hp:"180 ×2", damage:"75", dps:"90", range:"4,5 tiles", speed:"Rápida", description:"Atiradores ambidestros com cadência dupla de disparo.", portrait:commonArt(9,"fundibularios-de-benjamim") },
  { id:10, slug:"guardas-do-templo", name:"Guardas do Templo", rarity:"common", faith:3, type:"Tropa terrestre", hp:"450", damage:"110", dps:"85", range:"Corpo a corpo", speed:"Lenta", description:"Sentinela rígida com boa resistência contra tropas leves.", portrait:commonArt(10,"guardas-do-templo") },
  { id:11, slug:"sacerdote-levita", name:"Sacerdote Levita", rarity:"common", faith:3, type:"Suporte terrestre", hp:"280", damage:"Cura 45", dps:"Cura 40", range:"4 tiles", speed:"Média", description:"Restaura gradualmente a vida das tropas aliadas que permanecem próximas.", portrait:commonArt(11,"sacerdote-levita") },
  { id:12, slug:"escudeiros-da-fe", name:"Escudeiros da Fé", rarity:"common", faith:2, type:"Tropa defensiva (2)", hp:"250 ×2", damage:"40", dps:"40", range:"Corpo a corpo", speed:"Rápida", description:"Jovens protetores que avançam à frente do aliado mais próximo.", portrait:commonArt(12,"escudeiros-da-fe") },
  { id:13, slug:"guerreiros-de-naftali", name:"Guerreiros de Naftali", rarity:"common", faith:3, type:"Tropa terrestre (2)", hp:"310 ×2", damage:"105", dps:"95", range:"Corpo a corpo", speed:"Muito rápida", description:"Combatentes ágeis capazes de saltar o rio e surpreender a defesa rival.", portrait:commonArt(13,"guerreiros-de-naftali") },
  { id:14, slug:"construtores-de-muros", name:"Construtores de Muros", rarity:"common", faith:3, type:"Utilidade (2)", hp:"200 ×2", damage:"30", dps:"30", range:"Corpo a corpo", speed:"Média", description:"Erguem ao entrar uma barricada temporária com 200 pontos de vida.", portrait:commonArt(14,"construtores-de-muros") },
  { id:15, slug:"mensageiros-da-paz", name:"Mensageiros da Paz", rarity:"common", faith:1, type:"Tropa de ciclo", hp:"120", damage:"0", dps:"0", range:"Não ataca", speed:"Extrema", description:"Corre sem atacar para revelar armadilhas e desviar a atenção dos inimigos.", portrait:commonArt(15,"mensageiros-da-paz") },
  { id:16, slug:"caes-do-aprisco", name:"Cães do Aprisco", rarity:"common", faith:2, type:"Tropa terrestre (2)", hp:"140 ×2", damage:"60", dps:"70", range:"Corpo a corpo", speed:"Muito rápida", description:"Dupla veloz e leal que patrulha a arena e pressiona unidades isoladas.", portrait:commonArt(16,"caes-do-aprisco") },
  { id:17, slug:"esquadrao-de-honra", name:"Esquadrão de Honra", rarity:"common", faith:3, type:"Horda terrestre (5)", hp:"120 ×5", damage:"50", dps:"50", range:"Corpo a corpo", speed:"Média", description:"Formação numerosa para defesa de emergência e domínio de espaço.", portrait:commonArt(17,"esquadrao-de-honra") },
  { id:18, slug:"sentinelas-do-templo", name:"Sentinelas do Templo", rarity:"common", faith:3, type:"Tropa defensiva (2)", hp:"290 ×2", damage:"90", dps:"75", range:"Corpo a corpo", speed:"Média", description:"A guarda sagrada bloqueia completamente o primeiro ataque recebido.", portrait:commonArt(18,"sentinelas-do-templo") },
  { id:19, slug:"portadores-de-tocha", name:"Portadores de Tocha", rarity:"common", faith:2, type:"Tropa terrestre", hp:"220", damage:"70", dps:"80", range:"3 tiles", speed:"Rápida", description:"Mantém pressão a distância com chamas que causam dano contínuo.", portrait:commonArt(19,"portadores-de-tocha") },
  { id:20, slug:"vigias-da-muralha", name:"Vigias da Muralha", rarity:"common", faith:4, type:"Tropa de distância (3)", hp:"190 ×3", damage:"80", dps:"70", range:"5,5 tiles", speed:"Lenta", description:"Trio de arqueiros que assume posição e protege a muralha a longa distância.", portrait:commonArt(20,"vigias-da-muralha") }
];
