import { BIBLICAL_ARENAS, type ArenaPlayerProgression } from "./apostolic-arena-progression-v17";

type RGB = [number, number, number];
export type ArenaThemeV20 = {
  id: string; name: string; subtitle: string; obstacle: string; crossing: string; climate: string;
  sky: RGB; ambient: RGB; ground: RGB; lane: RGB; bridge: RGB; wall: RGB; water: RGB; waterGlow: RGB; sun: RGB;
  phases: readonly [{ name: string; description: string }, { name: string; description: string }, { name: string; description: string }];
};

export const ARENA_THEMES_V20: readonly ArenaThemeV20[] = [
  { id:"galilee",name:"Margens da Galileia",subtitle:"Primeiro Chamado",obstacle:"Lago da Galileia",crossing:"Cais de Pedra",climate:"Amanhecer",sky:[.12,.27,.38],ambient:[.55,.75,.82],ground:[.28,.36,.22],lane:[.48,.42,.27],bridge:[.55,.45,.3],wall:[.3,.28,.2],water:[.02,.35,.52],waterGlow:[.01,.24,.48],sun:[1,.78,.48],phases:[{name:"Redes Lançadas",description:"A batalha começa junto às aldeias de pescadores."},{name:"Vento sobre as Águas",description:"Ondas e vento atravessam o campo."},{name:"Chamado dos Discípulos",description:"A luz do amanhecer cobre toda a Arena."}]},
  { id:"elah",name:"Vale de Elá",subtitle:"Davi contra Golias",obstacle:"Riacho de Elá",crossing:"Passagens do Vale",climate:"Tarde seca",sky:[.34,.2,.1],ambient:[.74,.58,.4],ground:[.42,.3,.16],lane:[.55,.4,.22],bridge:[.62,.47,.27],wall:[.32,.22,.14],water:[.08,.25,.27],waterGlow:[.02,.18,.2],sun:[1,.58,.28],phases:[{name:"Exércitos em Espera",description:"As tendas ocupam os dois lados do vale."},{name:"Cinco Pedras",description:"O riacho revela o caminho do combate."},{name:"Vitória do Ungido",description:"Estandartes celebram a queda do gigante."}]},
  { id:"exodus",name:"Deserto do Êxodo",subtitle:"Caminho através das águas",obstacle:"Mar Aberto",crossing:"Caminhos nas Águas",climate:"Sol e areia",sky:[.42,.24,.1],ambient:[.8,.65,.45],ground:[.55,.39,.18],lane:[.68,.5,.26],bridge:[.78,.62,.36],wall:[.4,.28,.16],water:[.01,.3,.48],waterGlow:[.02,.28,.58],sun:[1,.7,.32],phases:[{name:"Acampamento Hebreu",description:"Tendas e dunas cercam o campo."},{name:"Coluna de Nuvem",description:"A sombra guia o avanço ao meio-dia."},{name:"Coluna de Fogo",description:"A batalha termina sob luz celestial."}]},
  { id:"jericho",name:"Muralhas de Jericó",subtitle:"A cidade fortificada",obstacle:"Fosso de Jericó",crossing:"Portões de Pedra",climate:"Poeira dourada",sky:[.3,.2,.14],ambient:[.7,.58,.45],ground:[.38,.29,.2],lane:[.5,.38,.25],bridge:[.58,.45,.3],wall:[.48,.34,.22],water:[.12,.25,.25],waterGlow:[.04,.18,.2],sun:[1,.65,.38],phases:[{name:"Primeira Volta",description:"As muralhas permanecem intactas."},{name:"Som das Trombetas",description:"Poeira e ecos anunciam o ataque."},{name:"Muralhas ao Chão",description:"Ruínas transformam as laterais da Arena."}]},
  { id:"gideon",name:"Acampamento de Gideão",subtitle:"Trezentos valentes",obstacle:"Vale de Jezreel",crossing:"Trilhas das Tochas",climate:"Noite estrelada",sky:[.025,.045,.11],ambient:[.22,.3,.48],ground:[.18,.18,.14],lane:[.3,.27,.18],bridge:[.42,.31,.18],wall:[.2,.18,.16],water:[.02,.14,.22],waterGlow:[.04,.22,.4],sun:[.45,.55,1],phases:[{name:"Cântaros Ocultos",description:"O acampamento dorme sob as estrelas."},{name:"Tochas Reveladas",description:"Luzes surgem nas duas rotas."},{name:"Espada do Senhor",description:"Clarões tomam o vale inteiro."}]},
  { id:"jerusalem",name:"Cidade de Davi",subtitle:"Reino de Jerusalém",obstacle:"Vale do Cedrom",crossing:"Pontes Reais",climate:"Pôr do sol",sky:[.3,.12,.14],ambient:[.58,.4,.45],ground:[.36,.27,.22],lane:[.49,.36,.28],bridge:[.62,.48,.3],wall:[.45,.35,.28],water:[.04,.2,.27],waterGlow:[.03,.18,.3],sun:[1,.44,.24],phases:[{name:"Portões da Cidade",description:"Guardas vigiam as muralhas reais."},{name:"Salão do Reino",description:"Bandeiras azuis e douradas são erguidas."},{name:"Trono de Davi",description:"A cidade resplandece ao pôr do sol."}]},
  { id:"carmel",name:"Monte Carmelo",subtitle:"Fogo do Céu",obstacle:"Ravina do Carmelo",crossing:"Altares de Pedra",climate:"Tempestade",sky:[.08,.08,.12],ambient:[.32,.34,.42],ground:[.24,.2,.16],lane:[.38,.3,.2],bridge:[.48,.37,.24],wall:[.3,.25,.2],water:[.03,.12,.18],waterGlow:[.05,.18,.3],sun:[1,.36,.12],phases:[{name:"Altar Restaurado",description:"Doze pedras marcam o centro do monte."},{name:"Silêncio dos Céus",description:"Nuvens escuras cobrem o campo."},{name:"Fogo Consumidor",description:"Chamas celestiais iluminam as torres."}]},
  { id:"covenant",name:"Templo da Aliança",subtitle:"Arena Celestial",obstacle:"Rio de Cristal",crossing:"Pontes da Glória",climate:"Luz sobrenatural",sky:[.04,.09,.2],ambient:[.45,.58,.9],ground:[.2,.22,.32],lane:[.28,.31,.44],bridge:[.65,.48,.18],wall:[.24,.24,.34],water:[.02,.32,.58],waterGlow:[.08,.38,.8],sun:[1,.8,.38],phases:[{name:"Átrio da Aliança",description:"Colunas douradas guardam o campo."},{name:"Rio de Cristal",description:"A luz corre entre as duas rotas."},{name:"Glória no Templo",description:"O cenário alcança sua forma celestial."}]}
] as const;

export type ArenaCompetitiveFieldV201 = { id: string; name: string; image: string; towerStyle: string; layout: string };
export const ARENA_COMPETITIVE_FIELDS_V201: Record<string, readonly [ArenaCompetitiveFieldV201, ArenaCompetitiveFieldV201]> = {
  galilee: [{id:"galilee-a",name:"Cais de Cafarnaum",image:"/games/apostolic-arena/arenas/v20-1/galilee-a.webp",towerStyle:"Faróis de pescadores",layout:"Píeres retos sobre o lago"},{id:"galilee-b",name:"Terraços da Galileia",image:"/games/apostolic-arena/arenas/v20-1/galilee-b.webp",towerStyle:"Cidadelas com velas",layout:"Pontes arqueadas e rotas curvas"}],
  elah: [{id:"elah-a",name:"Riacho das Cinco Pedras",image:"/games/apostolic-arena/arenas/v20-1/elah-a.webp",towerStyle:"Fortes de campanha",layout:"Travessias rasas no riacho"},{id:"elah-b",name:"Desfiladeiro do Gigante",image:"/games/apostolic-arena/arenas/v20-1/elah-b.webp",towerStyle:"Bastiões de funda",layout:"Rotas curvas entre rochedos"}],
  exodus: [{id:"exodus-a",name:"Caminho no Mar",image:"/games/apostolic-arena/arenas/v20-1/exodus-a.webp",towerStyle:"Santuários do Tabernáculo",layout:"Duas passagens entre as águas"},{id:"exodus-b",name:"Oásis da Coluna de Fogo",image:"/games/apostolic-arena/arenas/v20-1/exodus-b.webp",towerStyle:"Obeliscos do deserto",layout:"Pontes sobre o cânion"}],
  jericho: [{id:"jericho-a",name:"Portões de Jericó",image:"/games/apostolic-arena/arenas/v20-1/jericho-a.webp",towerStyle:"Torres cananeias",layout:"Avenidas de cerco e portões"},{id:"jericho-b",name:"Ruínas das Trombetas",image:"/games/apostolic-arena/arenas/v20-1/jericho-b.webp",towerStyle:"Torres reconstruídas",layout:"Rotas entre muralhas caídas"}],
  gideon: [{id:"gideon-a",name:"Vale das Tochas",image:"/games/apostolic-arena/arenas/v20-1/gideon-a.webp",towerStyle:"Torres de cântaros",layout:"Trilhas noturnas pelo riacho"},{id:"gideon-b",name:"Acampamento Midianita",image:"/games/apostolic-arena/arenas/v20-1/gideon-b.webp",towerStyle:"Fortes de tendas",layout:"Caminhos curvos entre acampamentos"}],
  jerusalem: [{id:"jerusalem-a",name:"Avenida Real",image:"/games/apostolic-arena/arenas/v20-1/jerusalem-a.webp",towerStyle:"Palácios de Davi",layout:"Pontes reais sobre o Cedrom"},{id:"jerusalem-b",name:"Cidade Alta",image:"/games/apostolic-arena/arenas/v20-1/jerusalem-b.webp",towerStyle:"Cidadelas de cedro",layout:"Aquedutos e terraços"}],
  carmel: [{id:"carmel-a",name:"Altar das Doze Pedras",image:"/games/apostolic-arena/arenas/v20-1/carmel-a.webp",towerStyle:"Altares fortificados",layout:"Travessias sobre a ravina"},{id:"carmel-b",name:"Fogo sobre o Monte",image:"/games/apostolic-arena/arenas/v20-1/carmel-b.webp",towerStyle:"Torres de chama",layout:"Pontes de basalto"}],
  covenant: [{id:"covenant-a",name:"Átrio do Templo",image:"/games/apostolic-arena/arenas/v20-1/covenant-a.webp",towerStyle:"Santuários salomônicos",layout:"Pontes douradas sobre cristal"},{id:"covenant-b",name:"Jardim da Nova Jerusalém",image:"/games/apostolic-arena/arenas/v20-1/covenant-b.webp",towerStyle:"Cidadelas celestiais",layout:"Calçadas de pérola e luz"}]
};

export function arenaThemeForProgression(progression: ArenaPlayerProgression) {
  const arenaIndex = BIBLICAL_ARENAS.reduce((latest, arena, index) => progression.trophies >= arena.trophies && progression.playerLevel >= arena.level ? index : latest, 0);
  const arena = BIBLICAL_ARENAS[arenaIndex]!;
  const next = BIBLICAL_ARENAS[arenaIndex + 1];
  const span = Math.max(1, (next?.trophies ?? arena.trophies + 900) - arena.trophies);
  const phaseIndex = Math.min(2, Math.floor(Math.max(0, progression.trophies - arena.trophies) / (span / 3)));
  return { arenaIndex, phaseIndex, arena, theme: ARENA_THEMES_V20[arenaIndex]!, phase: ARENA_THEMES_V20[arenaIndex]!.phases[phaseIndex]! };
}
