"use client";

import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {createClient} from "../lib/supabase/client";
import styles from "./apostolic-city-v165.module.css";

type Resource={amount:number;capacity:number;per_hour:number;last_synced_at:string};
type Option={building:string;name:string;description:string;costs:Record<string,number>;duration_seconds:number;required_level:number};
type Slot={slot:number;terrain:"land"|"coast";x:number;y:number;unlock_level:number;unlocked:boolean;building:string|null;building_level:number|null;state:string|null;next_costs:Record<string,number>|null;next_duration_seconds:number|null;options:Option[]};
type Data={server_now:string;city:{id:string;name:string;town_hall_level:number;population:number;capacity:number;satisfaction:number;visual_phase:number};resources:Record<string,Resource>;gold:{amount:number;per_hour:number};slots:Slot[];queue:{id:string;building:string;from_level:number;to_level:number;slot_no:number|null;costs:Record<string,number>;started_at:string;finishes_at:string}|null};

const names:Record<string,string>={town_hall:"Casa do Conselho",warehouse:"Celeiro da Aliança",farm:"Campos da Promessa",lumberyard:"Bosque de Cedros",quarry:"Pedreira dos Construtores",olive_press:"Lagar da Colheita",market:"Praça das Trocas",academy:"Casa da Sabedoria",tavern:"Mesa da Comunhão",museum:"Casa de Oração",barracks:"Pátio dos Guardiões",shipyard:"Arsenal do Mar",embassy:"Base Missionária",hideout:"Casa de Restauro"};
const icons:Record<string,string>={warehouse:"📦",farm:"🌾",lumberyard:"🌲",quarry:"🪨",olive_press:"🫒",market:"⚓",academy:"📜",tavern:"🍇",museum:"🏺",barracks:"🛡️",shipyard:"⛵",embassy:"🤝",hideout:"🕊️"};
const buildingAssets:Record<string,string>={town_hall:"casa-do-conselho-l1",warehouse:"celeiro-da-alianca-l1",farm:"campos-da-promessa-l1",lumberyard:"bosque-de-cedros-l1",quarry:"pedreira-dos-construtores-l1",olive_press:"lagar-da-colheita-l1",market:"praca-das-trocas-l1",academy:"casa-da-sabedoria-l1",tavern:"mesa-da-comunhao-l1",museum:"casa-de-oracao-l1",barracks:"patio-dos-guardioes-l1",shipyard:"arsenal-do-mar-l1",embassy:"base-missionaria-l1",hideout:"casa-de-restauro-l1"};
const resourceNames:Record<string,string>={wheat:"Trigo",cedar:"Cedro",stone:"Pedra",oil:"Azeite",gold:"Ouro"};
const resourceIcons:Record<string,string>={wheat:"🌾",cedar:"🪵",stone:"🪨",oil:"🫒",gold:"🪙"};
const resourceOrder=["wheat","cedar","stone","oil","gold"];
const phases=["","Aldeia inicial","Vila em crescimento","Cidade clássica","Metrópole","Império avançado"];
const duration=(seconds:number)=>seconds>=3600?`${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m`:`${Math.floor(seconds/60)}m ${seconds%60}s`;

export function ApostolicCityV165({onOpenProvince}:{onOpenProvince?:()=>void}){
 const[data,setData]=useState<Data|null>(null);
 const[selected,setSelected]=useState<number|null>(null);
 const[message,setMessage]=useState("");
 const[now,setNow]=useState(()=>Date.now());
 const[serverOffset,setServerOffset]=useState(0);
 const[busy,setBusy]=useState(false);
 const[visualPeriod,setVisualPeriod]=useState<"morning"|"afternoon"|"night">("morning");
 const settledQueue=useRef<string|null>(null);
 const load=useCallback(async()=>{const client=createClient();const{data:next,error}=await client.rpc("apostolic_sync_city_state");if(error){setMessage("Não foi possível sincronizar a cidade.");return}const city=next as Data;setServerOffset(new Date(city.server_now).getTime()-Date.now());setData(city)},[]);
 useEffect(()=>{void load();const sync=window.setInterval(()=>void load(),30000),clock=window.setInterval(()=>setNow(Date.now()),1000);return()=>{window.clearInterval(sync);window.clearInterval(clock)}},[load]);
 useEffect(()=>{const updatePeriod=()=>{const hour=new Date().getHours();setVisualPeriod(hour>=5&&hour<12?"morning":hour>=12&&hour<18?"afternoon":"night")};updatePeriod();const timer=window.setInterval(updatePeriod,60000);return()=>window.clearInterval(timer)},[]);
 const active=useMemo(()=>data?.slots.find(slot=>slot.slot===selected)??null,[data,selected]);
 const authoritativeNow=now+serverOffset;
 const remaining=data?.queue?Math.max(0,Math.ceil((new Date(data.queue.finishes_at).getTime()-authoritativeNow)/1000)):0;
 const queueTotal=data?.queue?Math.max(1,Math.ceil((new Date(data.queue.finishes_at).getTime()-new Date(data.queue.started_at).getTime())/1000)):1;
 const queueProgress=data?.queue?Math.min(100,Math.max(0,(queueTotal-remaining)/queueTotal*100)):0;
 useEffect(()=>{if(!data?.queue||remaining>0||settledQueue.current===data.queue.id)return;settledQueue.current=data.queue.id;void load().then(()=>setMessage("Obra concluída. A cidade foi atualizada automaticamente."))},[data?.queue,remaining,load]);
 const liveAmount=(resource:Resource)=>{const elapsed=Math.max(0,authoritativeNow-new Date(resource.last_synced_at).getTime())/3600000;return Math.min(resource.capacity,resource.amount+resource.per_hour*elapsed)};
 const start=async(option:Option)=>{if(!active||busy)return;setBusy(true);const{error}=await createClient().rpc("apostolic_start_slot_construction",{p_slot_no:active.slot,p_building:option.building,p_idempotency_key:crypto.randomUUID()});setMessage(error?.message??`${option.name} começou a ser construída.`);await load();setBusy(false)};
 const upgrade=async()=>{if(!active?.building||busy)return;setBusy(true);const{error}=await createClient().rpc("apostolic_start_building_upgrade",{p_building:active.building,p_idempotency_key:crypto.randomUUID()});setMessage(error?.message??`${names[active.building]??active.building} entrou em melhoria.`);await load();setBusy(false)};
 if(!data)return <section className={styles.loading}>Construindo a visão da cidade…</section>;
 const buildingPicture=(building:string,alt:string)=><picture><source srcSet={`/games/apostolic-journey/buildings/webp/${buildingAssets[building]}.webp`} type="image/webp"/><img className={styles.buildingImage} src={`/games/apostolic-journey/buildings/game/${buildingAssets[building]}.png`} alt={alt}/></picture>;
 return <section className={styles.shell} data-phase={data.city.visual_phase} data-time={visualPeriod}>
  <header><div><small>V181–V185 · CIDADE ISOMÉTRICA</small><h1>{data.city.name}</h1><p>{phases[data.city.visual_phase]} · Casa do Conselho nível {data.city.town_hall_level} · {visualPeriod==="morning"?"Manhã":visualPeriod==="afternoon"?"Tarde":"Noite"}</p></div><nav><button onClick={onOpenProvince}>MAPA DA PROVÍNCIA</button><button onClick={()=>void load()}>SINCRONIZAR</button></nav></header>
  {message&&<p className={styles.notice} role="status">{message}</p>}
  <section className={styles.resourceBar} aria-label="Recursos da cidade">{resourceOrder.map(key=>{const resource=data.resources[key];if(!resource)return null;const amount=liveAmount(resource);return <article key={key} data-full={amount>=resource.capacity}><span className={styles.resourceIcon}>{resourceIcons[key]}</span><div><small>{resourceNames[key]}</small><b>{Math.floor(amount).toLocaleString("pt-PT")}</b><em>+{resource.per_hour}/h</em></div><progress value={amount} max={resource.capacity}/></article>})}</section>
  <div className={styles.economy}><article><span>POPULAÇÃO</span><b>{data.city.population.toLocaleString("pt-PT")} / {data.city.capacity.toLocaleString("pt-PT")}</b><progress value={data.city.population} max={data.city.capacity}/></article><article><span>SATISFAÇÃO</span><b>{data.city.satisfaction}%</b><progress value={data.city.satisfaction} max={100}/></article>{data.queue?<article className={styles.queue}><span>OBRA EM ANDAMENTO</span><b>{names[data.queue.building]??data.queue.building} → Nv. {data.queue.to_level}</b><small>{remaining>0?duration(remaining):"Concluindo automaticamente…"}</small><progress value={queueProgress} max={100}/></article>:<article className={styles.queueEmpty}><span>CONSTRUÇÃO</span><b>Fila disponível</b><small>Escolha um terreno ou edifício no mapa.</small></article>}</div>
  <div className={styles.viewport}><div className={styles.cityMap}><button className={styles.hall} onClick={()=>setSelected(null)} aria-label={`Casa do Conselho, nível ${data.city.town_hall_level}`}>{buildingPicture("town_hall","Casa do Conselho")}<span className={styles.buildingLabel}><b>Casa do Conselho</b><small>Nível {data.city.town_hall_level}</small></span></button>{data.slots.map(slot=><button key={slot.slot} className={styles.slot} data-terrain={slot.terrain} data-locked={!slot.unlocked} data-selected={selected===slot.slot} data-building={Boolean(slot.building)} data-state={slot.state??"empty"} style={{left:`${slot.x}%`,top:`${slot.y}%`}} onClick={()=>setSelected(slot.slot)} aria-label={slot.building?`${names[slot.building]??slot.building}, nível ${slot.building_level}`:slot.unlocked?`Terreno ${slot.slot} disponível`:`Terreno bloqueado até nível ${slot.unlock_level}`}>{slot.building&&buildingAssets[slot.building]?buildingPicture(slot.building,names[slot.building]??slot.building):<span className={styles.groundMarker}>{slot.unlocked?"＋":"🔒"}</span>}<span className={styles.buildingLabel}><b>{slot.unlocked?slot.building?names[slot.building]??slot.building:`Terreno ${slot.slot}`:`Nível ${slot.unlock_level}`}</b>{slot.building_level!=null&&<small>{slot.state==="building"||slot.state==="upgrading"?"Em construção":`Nível ${slot.building_level}`}</small>}</span></button>)}</div></div>
  <aside className={styles.detail}>{active?<><small>{active.terrain==="coast"?"TERRENO COSTEIRO":"TERRENO URBANO"} · ÁREA {active.slot}</small><h2>{active.building?names[active.building]??active.building:active.unlocked?"Escolha uma construção":"Terreno bloqueado"}</h2>{!active.unlocked?<p>Evolua a Casa do Conselho para o nível {active.unlock_level}.</p>:active.building?<><p>Edifício nível {active.building_level}. A evolução altera a produção e o desenvolvimento visual da cidade.</p>{active.next_costs&&<p className={styles.costs}><b>Próxima melhoria:</b> {Object.entries(active.next_costs).map(([key,value])=>`${resourceIcons[key]??""} ${value}`).join(" · ")}{active.next_duration_seconds?` · ⏳ ${duration(active.next_duration_seconds)}`:""}</p>}<button disabled={Boolean(data.queue)||busy||active.building_level===0} onClick={()=>void upgrade()}>{data.queue?"FILA OCUPADA":"MELHORAR EDIFÍCIO"}</button></>:<div className={styles.catalog}>{active.options.length?active.options.map(option=><article key={option.building}>{buildingAssets[option.building]?buildingPicture(option.building,option.name):<span>{icons[option.building]??"🏠"}</span>}<div><h3>{names[option.building]??option.name}</h3><p>{option.description}</p><small>{Object.entries(option.costs).map(([key,value])=>`${resourceIcons[key]??""} ${value}`).join(" · ")} · ⏳ {duration(option.duration_seconds)}</small></div><button disabled={Boolean(data.queue)||busy} onClick={()=>void start(option)}>CONSTRUIR</button></article>):<p>Nenhum edifício compatível está disponível neste nível.</p>}</div>}</>:<><small>VISÃO DA CIDADE</small><h2>Escolha uma construção</h2><p>Os edifícios ocupam áreas isométricas da cidade. Estruturas marítimas ficam na costa; economia, pesquisa, comunhão, missão e defesa desenvolvem-se em terra.</p></>}</aside>
 </section>
}
