"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "../lib/supabase/client";
import styles from "./apostolic-colonization-center-v210.module.css";

type Island={code:string;name:string;description:string;biome:string;primary_resource:string;terrain_options:string[];distance_nm:number;exploration_seconds:number;foundation_seconds:number;capacity:number;occupied:number;town_hall_level:number;research_name:string;research_unlocked:boolean;discovered:boolean;colonized:boolean;exploration_costs:Record<string,number>;foundation_costs:Record<string,number>;visual_asset:string};
type Vessel={code:string;name:string;ready:number;capacity:number};
type Project={island_code:string;project_type:"exploration"|"foundation";terrain:string|null;colony_name:string|null;merchant_code:string;merchant_quantity:number;finishes_at:string};
type Colony={id:string;name:string;island_code:string;island_name:string;terrain:string;level:number;population:number;population_capacity:number;satisfaction:number;corruption:number;governor_hall_level:number;focus:string;resources:Record<string,{amount:number;capacity:number;per_hour:number}>};
type Data={capital:{name:string;town_hall_level:number};colony_limit:number;colony_count:number;islands:Island[];resources:Record<string,number>;merchant_fleet:Vessel[];active_project:Project|null;colonies:Colony[];history:{event:string;details:Record<string,string>;created_at:string}[]};
const icons:Record<string,string>={wheat:"🌾",cedar:"🪵",stone:"🪨",oil:"🫒",gold:"🪙"};
const terrains:Record<string,string>={olive_grove:"Olival da Promessa",harbor:"Enseada Protegida",highland:"Colina da Vigília",fertile_plain:"Campos da Aliança",quarry:"Pedreira dos Construtores",cedar_forest:"Bosque de Cedros"};
const focusNames:Record<string,string>={balanced:"Equilíbrio",harvest:"Colheita",construction:"Construção",mission:"Missão",defense:"Defesa"};
const duration=(s:number)=>s>=3600?`${Math.floor(s/3600)}h ${Math.ceil(s%3600/60)}m`:`${Math.ceil(s/60)} min`;
const cost=(value:Record<string,number>)=>Object.entries(value).map(([key,amount])=>`${icons[key]} ${amount}`).join(" · ");

export function ApostolicColonizationCenterV210(){
 const[data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[selected,setSelected]=useState(""),[merchant,setMerchant]=useState(""),[merchantQuantity,setMerchantQuantity]=useState(2),[terrain,setTerrain]=useState(""),[colonyName,setColonyName]=useState("Nova Comunidade"),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const load=useCallback(async()=>{const{data:next,error}=await createClient().rpc("apostolic_sync_colonization_center");if(error)setMessage(error.message);else setData(next as Data)},[]);
 useEffect(()=>{void load();const tick=setInterval(()=>setNow(Date.now()),1000),sync=setInterval(()=>void load(),30000);return()=>{clearInterval(tick);clearInterval(sync)}},[load]);
 useEffect(()=>{if(!selected&&data?.islands[0])setSelected(data.islands[0].code);if(!merchant&&data?.merchant_fleet[0])setMerchant(data.merchant_fleet[0].code)},[data,selected,merchant]);
 const island=data?.islands.find(item=>item.code===selected),vessel=data?.merchant_fleet.find(item=>item.code===merchant);
 useEffect(()=>{if(island&&!island.terrain_options.includes(terrain))setTerrain(island.terrain_options[0]??"")},[island,terrain]);
 const foundationLoad=useMemo(()=>island?Object.values(island.foundation_costs).reduce((sum,n)=>sum+n,0):0,[island]);
 const available=(key:string)=>data?.resources[key]??0,canPay=(values:Record<string,number>)=>Object.entries(values).every(([key,n])=>available(key)>=n);
 const left=data?.active_project?Math.max(0,Math.ceil((new Date(data.active_project.finishes_at).getTime()-now)/1000)):0;
 const explore=async()=>{if(!island||!merchant)return;setBusy(true);const{error}=await createClient().rpc("apostolic_start_island_exploration",{p_island_code:island.code,p_merchant_code:merchant,p_idempotency_key:crypto.randomUUID()});setMessage(error?.message??`A expedição partiu para ${island.name}.`);setBusy(false);void load()};
 const found=async()=>{if(!island||!merchant)return;setBusy(true);const{error}=await createClient().rpc("apostolic_found_colony",{p_island_code:island.code,p_terrain:terrain,p_name:colonyName,p_merchant_code:merchant,p_merchant_quantity:merchantQuantity,p_idempotency_key:crypto.randomUUID()});setMessage(error?.message??`A fundação de ${colonyName} foi iniciada.`);setBusy(false);void load()};
 const setFocus=async(colony:Colony,focus:string)=>{const{error}=await createClient().rpc("apostolic_set_colony_focus",{p_colony_id:colony.id,p_focus:focus,p_idempotency_key:crypto.randomUUID()});setMessage(error?.message??`${colony.name}: prioridade alterada para ${focusNames[focus]}.`);void load()};
 return <section className={styles.shell}>
  <header><div><small>V206–V210 · EXPANSÃO DAS ILHAS</small><h1>Novos Horizontes</h1><p>Explore com prudência, escolha o terreno e forme comunidades que cuidam das pessoas.</p></div><div className={styles.capacity}><span>CAPITAL <b>{data?.capital?.name??"—"}</b></span><span>COLÓNIAS <b>{data?.colony_count??0}/{data?.colony_limit??0}</b></span></div></header>
  {message&&<p className={styles.notice}>{message}</p>}
  {data?.active_project&&<article className={styles.active}><div><small>{data.active_project.project_type==="exploration"?"EXPEDIÇÃO DE EXPLORAÇÃO":"COMUNIDADE EM FUNDAÇÃO"}</small><h2>{data.islands.find(item=>item.code===data.active_project?.island_code)?.name}</h2><p>⛵ {data.active_project.merchant_quantity} navio(s) · {data.active_project.terrain?terrains[data.active_project.terrain]:"Cartografia costeira"}</p></div><b>{left?duration(left):"Concluindo…"}</b></article>}
  <div className={styles.layout}><div className={styles.map}>{data?.islands.map(item=><button key={item.code}type="button"data-selected={selected===item.code}data-discovered={item.discovered}onClick={()=>setSelected(item.code)}style={{backgroundImage:`linear-gradient(#06192199,#061921e8),url('${item.visual_asset}')`}}><span>{item.discovered?"🧭 DESCOBERTA":"🌫️ NÃO CARTOGRAFADA"}</span><strong>{item.name}</strong><small>{item.biome} · {item.distance_nm} milhas</small><em>{item.occupied}/{item.capacity} comunidades</em>{item.colonized&&<i>✓ COLONIZADA</i>}</button>)}</div>
   {island&&<aside className={styles.panel}><small>ILHA SELECIONADA</small><h2>{island.name}</h2><p>{island.description}</p><div className={styles.stats}><span>Recurso <b>{icons[island.primary_resource]} {island.primary_resource}</b></span><span>Câmara necessária <b>Nv. {island.town_hall_level}</b></span><span>Pesquisa <b>{island.research_name}</b></span></div><label>Navio mercante<select value={merchant}onChange={e=>setMerchant(e.target.value)}>{data?.merchant_fleet.map(v=><option key={v.code}value={v.code}>{v.name} · {v.ready} prontos · {v.capacity} carga</option>)}</select></label>{!island.discovered?<><p className={styles.cost}>{cost(island.exploration_costs)} · ⏳ {duration(island.exploration_seconds)}</p><button disabled={busy||Boolean(data?.active_project)||!island.research_unlocked||!canPay(island.exploration_costs)||(vessel?.ready??0)<1}onClick={()=>void explore()}>EXPLORAR ILHA</button></>:!island.colonized?<><label>Terreno<select value={terrain}onChange={e=>setTerrain(e.target.value)}>{island.terrain_options.map(option=><option key={option}value={option}>{terrains[option]}</option>)}</select></label><label>Nome da comunidade<input minLength={3}maxLength={32}value={colonyName}onChange={e=>setColonyName(e.target.value)}/></label><label>Navios de fundação<input type="number"min={2}max={10}value={merchantQuantity}onChange={e=>setMerchantQuantity(Math.max(2,Math.min(10,Number(e.target.value)||2)))}/></label><p className={styles.cost}>{cost(island.foundation_costs)} · 📦 {foundationLoad} · ⏳ {duration(island.foundation_seconds)}</p><button disabled={busy||Boolean(data?.active_project)||!canPay(island.foundation_costs)||(vessel?.ready??0)<merchantQuantity||(vessel?.capacity??0)*merchantQuantity<foundationLoad||(data?.colony_count??0)>=(data?.colony_limit??0)}onClick={()=>void found()}>FUNDAR COMUNIDADE</button></>:<p className={styles.done}>Esta ilha já possui uma comunidade sob a sua administração.</p>}</aside>}
  </div>
  <section className={styles.colonies}><h2>Administração das Comunidades</h2><div>{data?.colonies.map(colony=><article key={colony.id}><header><div><small>{colony.island_name}</small><h3>{colony.name}</h3></div><b>Nv. {colony.level}</b></header><p>👥 {colony.population}/{colony.population_capacity} · 😊 {colony.satisfaction}% · ⚖️ Corrupção {colony.corruption}%</p><div className={styles.resources}>{Object.entries(colony.resources).map(([key,value])=><span key={key}>{icons[key]} <b>{value.amount}</b><small>+{value.per_hour}/h</small></span>)}</div><label>Prioridade da comunidade<select value={colony.focus}onChange={e=>void setFocus(colony,e.target.value)}>{Object.entries(focusNames).map(([key,name])=><option key={key}value={key}>{name}</option>)}</select></label></article>)}</div>{!data?.colonies.length&&<p>Explore uma ilha e funde a primeira comunidade quando a Câmara Municipal e a frota estiverem preparadas.</p>}</section>
 </section>
}
