"use client";
import { useCallback,useEffect,useState,type FormEvent } from "react";
import { createClient } from "../lib/supabase/client";
import styles from "./arena-alliance-command-v85.module.css";
type Tab="agenda"|"diplomacy"|"mentoring"|"achievements"|"insights";
export function ArenaAllianceCommandV85(){
 const[data,setData]=useState<any>(null),[tab,setTab]=useState<Tab>("agenda"),[message,setMessage]=useState("");
 const load=useCallback(()=>{void createClient().rpc("arena_get_alliance_command_center").then(({data,error})=>{if(error)setMessage("Central indisponível.");else setData(data);});},[]);useEffect(load,[load]);
 const act=async(name:string,args:Record<string,unknown>,success:string)=>{const{error}=await createClient().rpc(name,args);setMessage(error?"Ação indisponível ou sem permissão.":success);load();};
 const createEvent=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);await act("arena_create_alliance_event",{p_title:String(f.get("title")),p_description:String(f.get("description")||""),p_kind:String(f.get("kind")),p_starts_at:new Date(String(f.get("starts"))).toISOString(),p_capacity:Number(f.get("capacity"))},"Evento adicionado à agenda.");};
 if(!data)return <section className={styles.shell}>{message||"A abrir Comando da Aliança…"}</section>;
 const tabs:Tab[]=["agenda","diplomacy","mentoring","achievements","insights"];
 return <section className={styles.shell}><header><div><small>V81–V85 · OPERAÇÕES</small><h2>Comando da Aliança</h2></div><nav>{tabs.map(x=><button key={x} data-active={tab===x} onClick={()=>setTab(x)}>{({agenda:"AGENDA",diplomacy:"DIPLOMACIA",mentoring:"MENTORIA",achievements:"CONQUISTAS",insights:"ANÁLISES"}as const)[x]}</button>)}</nav></header>{message&&<aside>{message}</aside>}
 {tab==="agenda"&&<div className={styles.panel}><form onSubmit={e=>void createEvent(e)}><input name="title" required minLength={3} placeholder="Título do evento"/><select name="kind"><option value="training">Treino</option><option value="study">Estudo</option><option value="war">Guerra</option><option value="tournament">Torneio</option><option value="community">Comunidade</option></select><input name="starts" type="datetime-local" required/><input name="capacity" type="number" min={2} max={50} defaultValue={20}/><input name="description" maxLength={300} placeholder="Descrição"/><button>PUBLICAR</button></form><div className={styles.cards}>{data.events.map((x:any)=><article key={x.id}><small>{x.kind.toUpperCase()} · {new Date(x.starts_at).toLocaleString("pt-BR")}</small><b>{x.title}</b><p>{x.description}</p><span>{x.attendees}/{x.capacity||50} confirmados</span><button disabled={x.joined} onClick={()=>void act("arena_join_alliance_event",{p_event_id:x.id},"Presença confirmada.")}>{x.joined?"CONFIRMADO":"PARTICIPAR"}</button></article>)}</div></div>}
 {tab==="diplomacy"&&<div className={styles.panel}><h3>Relações entre Alianças</h3><p>Propostas são criadas pela liderança e só ficam ativas após aceitação da outra Aliança.</p><div className={styles.cards}>{data.relations.map((x:any)=><article key={x.id}><small>{x.kind.toUpperCase()}</small><b>{x.alliance_name}</b><span>{x.status}</span>{x.status==="pending"&&x.target_alliance_id&&<div><button onClick={()=>void act("arena_respond_alliance_relation",{p_relation_id:x.id,p_accept:true},"Aliança diplomática confirmada.")}>ACEITAR</button><button onClick={()=>void act("arena_respond_alliance_relation",{p_relation_id:x.id,p_accept:false},"Proposta recusada.")}>RECUSAR</button></div>}</article>)}</div></div>}
 {tab==="mentoring"&&<div className={styles.panel}><h3>Academia de Guardiões</h3><div className={styles.actions}><button onClick={()=>void act("arena_set_alliance_mentor_preference",{p_preference:"mentor"},"Você entrou como mentor.")}>QUERO ENSINAR</button><button onClick={()=>void act("arena_set_alliance_mentor_preference",{p_preference:"apprentice"},"Você entrou como aprendiz.")}>QUERO APRENDER</button></div><div className={styles.cards}>{data.mentor_pool.map((x:any)=><article key={x.user_id}><b>{x.display_name}</b><span>{x.preference==="mentor"?"Mentor disponível":"Procura mentor"}</span></article>)}</div></div>}
 {tab==="achievements"&&<div className={styles.cards}>{data.achievements.map((x:any)=>{const done=x.value>=x.target;return <article key={x.id} data-done={done}><small>{done?"CONCLUÍDA":"EM PROGRESSO"}</small><b>{x.title}</b><p>{x.description}</p><progress value={Math.min(x.value,x.target)} max={x.target}/><span>{x.value}/{x.target} · {x.reward}</span></article>})}</div>}
 {tab==="insights"&&<div className={styles.metrics}>{Object.entries(data.metrics).map(([key,value])=><article key={key}><strong>{String(value)}</strong><span>{key.replaceAll("_"," ")}</span></article>)}</div>}</section>;
}
