"use client";

import Image from "next/image";
import { FormEvent, useEffect, useRef, useState } from "react";
import { createClient } from "../lib/supabase/client";

type ChatMessage={id:string;role:"user"|"assistant";content:string;avatarState:string;actions?:{label:string;kind:string;value?:string}[]};
type Settings={enabled:boolean;display_name:string;greeting:string;tone:string;show_avatar_every_message:boolean;animations_enabled:boolean;allow_channel_recommendations:boolean;allow_thread_summary:boolean;allow_lumi_handoff:boolean};
const defaults:Settings={enabled:true,display_name:"Barnabé",greeting:"A paz! Sou Barnabé, o guia virtual da comunidade. Como posso ajudar?",tone:"acolhedor",show_avatar_every_message:true,animations_enabled:true,allow_channel_recommendations:true,allow_thread_summary:true,allow_lumi_handoff:true};

export function CommunityBarnabasChat({circleId,channelId,userId,userAvatar,memberRole,onSelectChannel}:{circleId:string;channelId:string;userId:string;userAvatar:string|null;memberRole:string;onSelectChannel:(id:string)=>void}){
  const [open,setOpen]=useState(false),[thinking,setThinking]=useState(false),[conversationId,setConversationId]=useState<string|null>(null),[settings,setSettings]=useState(defaults),[messages,setMessages]=useState<ChatMessage[]>([]),[error,setError]=useState("");
  const endRef=useRef<HTMLDivElement>(null); const canManage=["owner","moderator"].includes(memberRole);
  useEffect(()=>{if(!circleId)return;let active=true;const load=async()=>{const supabase=createClient();const setting=await supabase.from("community_bot_settings").select("enabled,display_name,greeting,tone,show_avatar_every_message,animations_enabled,allow_channel_recommendations,allow_thread_summary,allow_lumi_handoff").eq("circle_id",circleId).maybeSingle();if(setting.data&&active)setSettings(setting.data as Settings);const conversation=await supabase.from("community_bot_conversations").select("id").eq("circle_id",circleId).eq("user_id",userId).order("updated_at",{ascending:false}).limit(1).maybeSingle();if(conversation.data&&active){setConversationId(conversation.data.id);const history=await supabase.from("community_bot_messages").select("id,role,content,avatar_state").eq("conversation_id",conversation.data.id).order("created_at").limit(40);if(active)setMessages(((history.data??[]) as {id:string;role:"user"|"assistant";content:string;avatar_state:string}[]).map(item=>({...item,avatarState:item.avatar_state})));}};void load();return()=>{active=false;};},[circleId,userId]);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[messages,thinking]);
  async function sendText(text:string){const question=text.trim();if(!question||thinking)return;setError("");setThinking(true);setMessages(current=>[...current,{id:crypto.randomUUID(),role:"user",content:question,avatarState:"greeting"}]);try{const response=await fetch("/api/community-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,circleId,channelId,conversationId})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Não foi possível responder.");setConversationId(result.conversationId);setMessages(current=>[...current,{id:crypto.randomUUID(),role:"assistant",content:result.answer,avatarState:result.avatarState,actions:result.actions}]);}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível responder.");}finally{setThinking(false);}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const data=new FormData(form);form.reset();await sendText(String(data.get("message")??""));}
  function action(kind:string,value?:string,label?:string){if(kind==="channel"&&value){onSelectChannel(value);setOpen(false);}else if(kind==="lumi"&&value){window.location.href=`/dashboard?section=bible&ask=${encodeURIComponent(value)}`;}else if(kind==="prompt")void sendText(label??"");}
  async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const next={enabled:form.get("enabled")==="on",display_name:String(form.get("display_name")),greeting:String(form.get("greeting")),tone:String(form.get("tone")),show_avatar_every_message:form.get("show_avatar_every_message")==="on",animations_enabled:form.get("animations_enabled")==="on",allow_channel_recommendations:form.get("allow_channel_recommendations")==="on",allow_thread_summary:form.get("allow_thread_summary")==="on",allow_lumi_handoff:form.get("allow_lumi_handoff")==="on"};const {error}=await createClient().from("community_bot_settings").upsert({circle_id:circleId,updated_by:userId,...next});if(error)setError("Não foi possível guardar as configurações.");else{setSettings(next);setError("Configurações guardadas.");}}
  if(!circleId||!settings.enabled&&!canManage)return null;
  return <div className={`barnabas-chat ${open?"is-open":""} ${settings.animations_enabled?"has-motion":""}`}>
    {!open&&<button className="barnabas-chat-launcher" type="button" onClick={()=>setOpen(true)}><Image src="/characters/lumi/community-barnabas-chat-v3.png" width={92} height={92} alt=""/><span><strong>{settings.display_name}</strong><small>Guia virtual com IA</small></span><em>1</em></button>}
    {open&&<section className="barnabas-chat-window" aria-label={`Chat com ${settings.display_name}`}>
      <header><Image src="/characters/lumi/community-barnabas-chat-v3.png" width={64} height={64} alt=""/><span><strong>{settings.display_name}</strong><small><i/> Guia virtual com IA</small></span><button type="button" onClick={()=>setOpen(false)} aria-label="Minimizar chat">—</button><button type="button" onClick={()=>setOpen(false)} aria-label="Fechar chat">×</button></header>
      <div className="barnabas-chat-history" aria-live="polite">
        {messages.length===0&&<article className="is-assistant"><Image src="/characters/lumi/community-barnabas-chat-v3.png" width={44} height={44} alt="Barnabé"/><div><strong>{settings.display_name} <small>IA</small></strong><p>{settings.greeting}</p></div></article>}
        {messages.map(message=><article key={message.id} className={message.role==="assistant"?"is-assistant":"is-user"}>{message.role==="assistant"&&settings.show_avatar_every_message?<Image src={message.avatarState==="studying"?"/characters/lumi/community-barnabas-study-v2.png":"/characters/lumi/community-barnabas-chat-v3.png"} width={44} height={44} alt="Barnabé"/>:message.role==="user"&&<span className="barnabas-user-avatar" style={userAvatar?{backgroundImage:`url("${userAvatar}")`}:undefined}>{userAvatar?"":"EU"}</span>}<div><strong>{message.role==="assistant"?`${settings.display_name} · IA`:"Você"}</strong><p>{message.content}</p>{message.actions?.length?<footer>{message.actions.map(item=><button key={item.label} type="button" onClick={()=>action(item.kind,item.value,item.label)}>{item.label}</button>)}</footer>:null}</div></article>)}
        {thinking&&<article className="is-assistant is-thinking"><Image src="/characters/lumi/community-barnabas-study-v2.png" width={44} height={44} alt=""/><div><strong>{settings.display_name}</strong><p><span/><span/><span/> pensando…</p></div></article>}<div ref={endRef}/>
      </div>
      <div className="barnabas-quick-actions"><button onClick={()=>void sendText("Onde devo publicar esta dúvida?")}># Canal certo</button><button onClick={()=>void sendText("Resuma este canal")}>Resumo</button><button onClick={()=>void sendText("Quero chamar um tutor")}>Tutor</button></div>
      <form className="barnabas-chat-composer" onSubmit={submit}><input name="message" maxLength={1000} required placeholder="Pergunte ao Barnabé…"/><button disabled={thinking} aria-label="Enviar">➤</button></form>
      <small className="barnabas-disclaimer">Guia inspirado em Barnabé. A IA pode cometer erros; confirme informações importantes.</small>{error&&<p className="barnabas-chat-error" role="status">{error}</p>}
      {canManage&&<details className="barnabas-admin"><summary>⚙ Configurar Barnabé</summary><form onSubmit={saveSettings}><label>Nome<input name="display_name" defaultValue={settings.display_name} minLength={2} maxLength={40}/></label><label>Saudação<textarea name="greeting" defaultValue={settings.greeting} minLength={10} maxLength={300}/></label><label>Tom<select name="tone" defaultValue={settings.tone}><option value="acolhedor">Acolhedor</option><option value="direto">Direto</option><option value="academico">Académico</option></select></label>{[["enabled","Ativo"],["show_avatar_every_message","Avatar em cada resposta"],["animations_enabled","Animações"],["allow_channel_recommendations","Recomendar canais"],["allow_thread_summary","Resumir conversas"],["allow_lumi_handoff","Encaminhar à Lumi"]].map(([name,label])=><label className="barnabas-check" key={name}><input type="checkbox" name={name} defaultChecked={Boolean(settings[name as keyof Settings])}/>{label}</label>)}<button className="button button-secondary">Guardar</button></form></details>}
    </section>}
  </div>;
}
