begin;

-- V166: a Câmara ocupa o centro cívico; os doze lotes ficam disponíveis para edifícios.
update public.apostolic_city_buildings set slot_no=null where building='town_hall';
update public.apostolic_city_buildings set slot_no=null where building in('lumberyard','quarry','olive_press','academy');

-- V167: catálogo urbano e costeiro original da Jornada das Nações.
alter table public.apostolic_building_catalog drop constraint apostolic_building_catalog_building_check;
alter table public.apostolic_building_catalog add constraint apostolic_building_catalog_building_check check(building in('town_hall','warehouse','farm','lumberyard','quarry','olive_press','market','academy','barracks','wall','infirmary','tavern','museum','shipyard','embassy','hideout'));
alter table public.apostolic_city_buildings drop constraint apostolic_city_buildings_building_check;
alter table public.apostolic_city_buildings add constraint apostolic_city_buildings_building_check check(building in('town_hall','warehouse','farm','lumberyard','quarry','olive_press','market','academy','barracks','wall','infirmary','tavern','museum','shipyard','embassy','hideout'));
alter table public.apostolic_building_catalog add column terrain text not null default'land'check(terrain in('land','coast','civic')),add column required_town_hall_level smallint not null default 1 check(required_town_hall_level between 1 and 100),add column category text not null default'economy'check(category in('administration','satisfaction','economy','military','research','diplomacy'));
update public.apostolic_building_catalog set terrain=case when building='town_hall'then'civic'when building='market'then'coast'else'land'end,category=case when building in('town_hall','warehouse')then'administration'when building='academy'then'research'else'economy'end;
insert into public.apostolic_building_catalog(building,name,description,max_level,base_duration_seconds,duration_growth,base_costs,cost_growth,sort_order,terrain,required_town_hall_level,category)values
('tavern','Casa da Comunhão','Aumenta a satisfação e sustenta o crescimento da população.',40,70,1.32,'{"cedar":70,"stone":45,"gold":35}',1.42,12,'land',1,'satisfaction'),
('museum','Casa da Memória','Preserva histórias e amplia a satisfação dos cidadãos.',40,110,1.35,'{"cedar":90,"stone":120,"gold":70}',1.46,13,'land',5,'satisfaction'),
('hideout','Casa dos Batedores','Abriga batedores e fortalece a contravigilância.',40,95,1.34,'{"cedar":110,"stone":75,"oil":35}',1.45,14,'land',5,'military'),
('embassy','Casa das Alianças','Coordena diplomacia, alianças e tratados entre cidades.',40,120,1.36,'{"cedar":130,"stone":110,"gold":100}',1.47,15,'land',8,'diplomacy'),
('shipyard','Estaleiro da Aliança','Constrói e mantém embarcações de defesa marítima.',40,130,1.36,'{"cedar":170,"stone":95,"oil":60}',1.47,16,'coast',10,'military');

-- V168: a fila passa a conhecer o terreno onde a obra acontece.
alter table public.apostolic_construction_queue add column slot_no smallint references public.apostolic_city_slot_catalog(slot_no);

-- V169: início atômico, idempotente e validado pelo proprietário.
create or replace function public.apostolic_start_slot_construction(p_slot_no integer,p_building text,p_idempotency_key uuid)returns jsonb language plpgsql security definer set search_path=''as $$
declare uid uuid:=(select auth.uid());cid uuid;town_level integer;slot public.apostolic_city_slot_catalog%rowtype;cat public.apostolic_building_catalog%rowtype;r record;cost bigint;finish_at timestamptz;
begin
 if uid is null then raise exception'authentication required';end if;if p_idempotency_key is null then raise exception'idempotency key required';end if;
 select c.id,b.level into cid,town_level from public.apostolic_cities c join public.apostolic_city_buildings b on b.city_id=c.id and b.building='town_hall'where c.owner_id=uid for update of c;
 if cid is null then raise exception'city not found';end if;
 if exists(select 1 from public.apostolic_construction_queue where city_id=cid and idempotency_key=p_idempotency_key)then return public.apostolic_get_city_management();end if;
 if exists(select 1 from public.apostolic_construction_queue where city_id=cid and status='building')then raise exception'construction queue occupied';end if;
 select*into slot from public.apostolic_city_slot_catalog where slot_no=p_slot_no;if not found or town_level<slot.unlock_town_hall_level then raise exception'slot locked';end if;
 if exists(select 1 from public.apostolic_city_buildings where city_id=cid and slot_no=p_slot_no)then raise exception'slot occupied';end if;
 select*into cat from public.apostolic_building_catalog where building=p_building;if not found or cat.terrain<>slot.terrain or town_level<cat.required_town_hall_level or cat.terrain='civic'then raise exception'building unavailable for slot';end if;
 if exists(select 1 from public.apostolic_city_buildings where city_id=cid and building=p_building)then raise exception'building already exists';end if;
 for r in select key,value from jsonb_each_text(cat.base_costs)loop cost:=r.value::bigint;if not exists(select 1 from public.apostolic_city_resources where city_id=cid and resource=r.key and amount>=cost)then raise exception'insufficient resource: %',r.key;end if;end loop;
 for r in select key,value from jsonb_each_text(cat.base_costs)loop cost:=r.value::bigint;update public.apostolic_city_resources set amount=amount-cost,updated_at=clock_timestamp()where city_id=cid and resource=r.key;insert into public.apostolic_resource_ledger(city_id,resource,delta,balance_after,reason,idempotency_key)select cid,r.key,-cost,amount,'new_building:'||p_building,p_idempotency_key from public.apostolic_city_resources where city_id=cid and resource=r.key;end loop;
 finish_at:=clock_timestamp()+make_interval(secs=>cat.base_duration_seconds);
 insert into public.apostolic_city_buildings(city_id,building,level,state,finishes_at,slot_no)values(cid,p_building,0,'building',finish_at,p_slot_no);
 insert into public.apostolic_construction_queue(city_id,building,from_level,to_level,costs,finishes_at,idempotency_key,slot_no)values(cid,p_building,0,1,cat.base_costs,finish_at,p_idempotency_key,p_slot_no);
 return public.apostolic_get_city_management();
end;$$;

-- V170: conclusão e painel visual unificados para obras novas e melhorias.
create or replace function public.apostolic_finish_city_construction()returns jsonb language plpgsql security definer set search_path=''as $$declare uid uuid:=(select auth.uid());cid uuid;q public.apostolic_construction_queue%rowtype;bonus integer;begin if uid is null then raise exception'authentication required';end if;select id into cid from public.apostolic_cities where owner_id=uid for update;if cid is null then raise exception'city not found';end if;select*into q from public.apostolic_construction_queue where city_id=cid and status='building'for update;if not found then return public.apostolic_get_city_management();end if;if q.finishes_at>clock_timestamp()then raise exception'construction still in progress';end if;update public.apostolic_city_buildings set level=q.to_level,state='ready',finishes_at=null,updated_at=clock_timestamp()where city_id=cid and building=q.building;update public.apostolic_construction_queue set status='completed',completed_at=clock_timestamp()where id=q.id;if q.building='warehouse'then update public.apostolic_cities set warehouse_level=q.to_level,updated_at=clock_timestamp()where id=cid;update public.apostolic_city_resources set capacity=1000+(q.to_level-1)*500,updated_at=clock_timestamp()where city_id=cid;elsif q.building='town_hall'then update public.apostolic_cities set level=q.to_level,updated_at=clock_timestamp()where id=cid;elsif q.building='tavern'then update public.apostolic_cities set satisfaction=least(1000,satisfaction+15),updated_at=clock_timestamp()where id=cid;elsif q.building='museum'then update public.apostolic_cities set satisfaction=least(1000,satisfaction+25),updated_at=clock_timestamp()where id=cid;else bonus:=case q.building when'farm'then 30 when'lumberyard'then 20 when'quarry'then 20 when'olive_press'then 12 else 0 end;if bonus>0 then update public.apostolic_city_resources set production_per_hour=production_per_hour+bonus,updated_at=clock_timestamp()where city_id=cid and resource=case q.building when'farm'then'wheat'when'lumberyard'then'cedar'when'quarry'then'stone'else'oil'end;end if;end if;return public.apostolic_get_city_management();end;$$;
create or replace function public.apostolic_get_city_management()returns jsonb language sql stable security definer set search_path=''as $$with own as(select c.*,b.level town_level from public.apostolic_cities c join public.apostolic_city_buildings b on b.city_id=c.id and b.building='town_hall'where c.owner_id=(select auth.uid()))select coalesce((select jsonb_build_object('city',jsonb_build_object('id',o.id,'name',o.name,'town_hall_level',o.town_level,'population',o.population,'capacity',60+o.town_level*40,'satisfaction',o.satisfaction,'visual_phase',case when o.town_level<=3 then 1 when o.town_level<=9 then 2 when o.town_level<=15 then 3 when o.town_level<=24 then 4 else 5 end),'gold',(select jsonb_build_object('amount',amount,'per_hour',production_per_hour+floor(o.population*.25))from public.apostolic_city_resources where city_id=o.id and resource='gold'),'slots',(select jsonb_agg(jsonb_build_object('slot',s.slot_no,'terrain',s.terrain,'x',s.x,'y',s.y,'unlock_level',s.unlock_town_hall_level,'unlocked',o.town_level>=s.unlock_town_hall_level,'building',b.building,'building_level',b.level,'state',b.state,'options',(select coalesce(jsonb_agg(jsonb_build_object('building',cat.building,'name',cat.name,'description',cat.description,'costs',cat.base_costs,'duration_seconds',cat.base_duration_seconds,'required_level',cat.required_town_hall_level)order by cat.sort_order),'[]'::jsonb)from public.apostolic_building_catalog cat where cat.terrain=s.terrain and cat.required_town_hall_level<=o.town_level and not exists(select 1 from public.apostolic_city_buildings used where used.city_id=o.id and used.building=cat.building)))order by s.slot_no)from public.apostolic_city_slot_catalog s left join public.apostolic_city_buildings b on b.city_id=o.id and b.slot_no=s.slot_no),'queue',(select to_jsonb(q)from(select building,to_level,slot_no,finishes_at from public.apostolic_construction_queue where city_id=o.id and status='building'limit 1)q))from own o),'null'::jsonb)$$;
revoke all on function public.apostolic_start_slot_construction(integer,text,uuid)from public,anon,authenticated;grant execute on function public.apostolic_start_slot_construction(integer,text,uuid)to authenticated;
revoke all on function public.apostolic_finish_city_construction(),public.apostolic_get_city_management()from public,anon,authenticated;grant execute on function public.apostolic_finish_city_construction(),public.apostolic_get_city_management()to authenticated;
commit;
