begin;

create table public.arena_alliance_emblem_catalog(
 id text primary key check(id~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),name text not null,image_path text not null,
 tier text not null check(tier in('free','gems','pro')),gem_price integer check(gem_price is null or gem_price between 1 and 10000),
 sort_order integer not null unique,active boolean not null default true,check((tier='gems')=(gem_price is not null))
);
insert into public.arena_alliance_emblem_catalog(id,name,image_path,tier,gem_price,sort_order)values
('pomba-da-alianca','Pomba da Aliança','/images/arena/alliance-emblems-v63/pomba-da-alianca.webp','free',null,1),
('lampada-da-vigilia','Lâmpada da Vigília','/images/arena/alliance-emblems-v63/lampada-da-vigilia.webp','free',null,2),
('trigo-da-colheita','Trigo da Colheita','/images/arena/alliance-emblems-v63/trigo-da-colheita.webp','free',null,3),
('monte-da-promessa','Monte da Promessa','/images/arena/alliance-emblems-v63/monte-da-promessa.webp','free',null,4),
('leao-de-juda','Leão de Judá','/images/arena/alliance-emblems-v63/leao-de-juda.webp','gems',500,5),
('arca-sobre-as-aguas','Arca sobre as Águas','/images/arena/alliance-emblems-v63/arca-sobre-as-aguas.webp','gems',450,6),
('trombetas-de-jerico','Trombetas de Jericó','/images/arena/alliance-emblems-v63/trombetas-de-jerico.webp','gems',550,7),
('fogo-do-carmelo','Fogo do Carmelo','/images/arena/alliance-emblems-v63/fogo-do-carmelo.webp','gems',650,8),
('coroa-das-doze-estrelas','Coroa das Doze Estrelas','/images/arena/alliance-emblems-v63/coroa-das-doze-estrelas.webp','pro',null,9),
('portoes-de-safira','Portões de Safira','/images/arena/alliance-emblems-v63/portoes-de-safira.webp','pro',null,10),
('espada-dos-serafins','Espada dos Serafins','/images/arena/alliance-emblems-v63/espada-dos-serafins.webp','pro',null,11),
('selo-da-nova-alianca','Selo da Nova Aliança','/images/arena/alliance-emblems-v63/selo-da-nova-alianca.webp','pro',null,12);

alter table public.arena_alliances add column emblem_id text not null default'pomba-da-alianca' references public.arena_alliance_emblem_catalog(id);
create table public.arena_alliance_emblem_unlocks(alliance_id uuid not null references public.arena_alliances(id)on delete cascade,emblem_id text not null references public.arena_alliance_emblem_catalog(id),purchased_by uuid not null references public.profiles(id)on delete restrict,gem_price integer not null check(gem_price>0),unlocked_at timestamptz not null default now(),primary key(alliance_id,emblem_id));
alter table public.arena_alliance_emblem_catalog enable row level security;alter table public.arena_alliance_emblem_catalog force row level security;alter table public.arena_alliance_emblem_unlocks enable row level security;alter table public.arena_alliance_emblem_unlocks force row level security;
revoke all on public.arena_alliance_emblem_catalog,public.arena_alliance_emblem_unlocks from anon,authenticated;

create or replace function public.arena_alliance_can_use_emblem(p_alliance_id uuid,p_emblem_id text)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.arena_alliances a join public.arena_alliance_emblem_catalog c on c.id=p_emblem_id and c.active where a.id=p_alliance_id and(public.arena_alliance_has_pro(a.id)or c.tier='free'or(c.tier='gems'and exists(select 1 from public.arena_alliance_emblem_unlocks u where u.alliance_id=a.id and u.emblem_id=c.id))))$$;
create or replace function public.arena_alliance_effective_emblem(p_alliance_id uuid)returns text language sql stable security definer set search_path=''as $$select case when public.arena_alliance_can_use_emblem(a.id,a.emblem_id)then a.emblem_id else'pomba-da-alianca'end from public.arena_alliances a where a.id=p_alliance_id$$;

create or replace function public.arena_get_alliance_emblems()returns jsonb language plpgsql stable security definer set search_path=''as $$declare v_user uuid:=(select auth.uid());v_alliance uuid;v_role text;v_gems bigint;v_pro boolean;begin if v_user is null then raise exception'authentication required';end if;select alliance_id,role into v_alliance,v_role from public.arena_alliance_members where user_id=v_user;if v_alliance is null then raise exception'alliance required';end if;select gems into v_gems from public.arena_player_wallets where user_id=v_user;v_pro:=public.arena_alliance_has_pro(v_alliance);return jsonb_build_object('is_pro',v_pro,'can_manage',v_role in('founder','elder'),'wallet_gems',coalesce(v_gems,0),'emblems',(select jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'image',c.image_path,'tier',c.tier,'price',c.gem_price,'unlocked',v_pro or c.tier='free'or exists(select 1 from public.arena_alliance_emblem_unlocks u where u.alliance_id=v_alliance and u.emblem_id=c.id))order by c.sort_order) from public.arena_alliance_emblem_catalog c where c.active));end;$$;

create or replace function public.arena_purchase_alliance_emblem(p_emblem_id text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path=''as $$declare v_user uuid:=(select auth.uid());v_alliance uuid;v_role text;v_item public.arena_alliance_emblem_catalog%rowtype;v_wallet public.arena_player_wallets%rowtype;begin if v_user is null then raise exception'authentication required';end if;if p_idempotency_key is null or length(p_idempotency_key)<16 then raise exception'invalid idempotency key';end if;select alliance_id,role into v_alliance,v_role from public.arena_alliance_members where user_id=v_user;if v_alliance is null or v_role not in('founder','elder')then raise exception'alliance manager required';end if;select*into v_item from public.arena_alliance_emblem_catalog where id=p_emblem_id and tier='gems'and active;if not found then raise exception'emblem not purchasable';end if;if public.arena_alliance_has_pro(v_alliance)then return jsonb_build_object('unlocked',true,'included_with_pro',true,'emblem_id',v_item.id);end if;if exists(select 1 from public.arena_alliance_emblem_unlocks where alliance_id=v_alliance and emblem_id=v_item.id)then return jsonb_build_object('unlocked',true,'already_owned',true,'emblem_id',v_item.id);end if;insert into public.arena_player_wallets(user_id)values(v_user)on conflict(user_id)do nothing;select*into v_wallet from public.arena_player_wallets where user_id=v_user for update;if exists(select 1 from public.arena_wallet_transactions where idempotency_key=p_idempotency_key)then return jsonb_build_object('unlocked',exists(select 1 from public.arena_alliance_emblem_unlocks where alliance_id=v_alliance and emblem_id=v_item.id),'replayed',true,'gems',v_wallet.gems);end if;if v_wallet.gems<v_item.gem_price then raise exception'insufficient gems';end if;update public.arena_player_wallets set gems=gems-v_item.gem_price where user_id=v_user returning*into v_wallet;insert into public.arena_wallet_transactions(user_id,currency,amount,transaction_type,source,reference_id,idempotency_key)values(v_user,'gems',-v_item.gem_price,'spend','alliance-emblem',v_alliance::text||':'||v_item.id,p_idempotency_key);insert into public.arena_alliance_emblem_unlocks(alliance_id,emblem_id,purchased_by,gem_price)values(v_alliance,v_item.id,v_user,v_item.gem_price);insert into public.arena_alliance_activities(alliance_id,actor_id,kind,message)values(v_alliance,v_user,'system','Um novo brasão foi desbloqueado para a Aliança.');return jsonb_build_object('unlocked',true,'emblem_id',v_item.id,'gems',v_wallet.gems);end;$$;

create or replace function public.arena_select_alliance_emblem(p_emblem_id text)returns jsonb language plpgsql security definer set search_path=''as $$declare v_user uuid:=(select auth.uid());v_alliance uuid;v_role text;begin if v_user is null then raise exception'authentication required';end if;select alliance_id,role into v_alliance,v_role from public.arena_alliance_members where user_id=v_user;if v_alliance is null or v_role not in('founder','elder')then raise exception'alliance manager required';end if;if not public.arena_alliance_can_use_emblem(v_alliance,p_emblem_id)then raise exception'emblem locked';end if;update public.arena_alliances set emblem_id=p_emblem_id where id=v_alliance;insert into public.arena_alliance_activities(alliance_id,actor_id,kind,message)values(v_alliance,v_user,'system','A Aliança apresentou um novo brasão.');return jsonb_build_object('selected',true,'emblem_id',p_emblem_id,'is_pro',public.arena_alliance_has_pro(v_alliance));end;$$;

create or replace function public.arena_browse_alliances(p_query text default'',p_limit integer default 12)returns jsonb language sql stable security definer set search_path=''as $$select coalesce(jsonb_agg(row_data order by weekly_glory desc,member_count desc),'[]'::jsonb)from(select a.id,a.name,a.tag,a.description,a.emblem,a.emblem_id,public.arena_alliance_effective_emblem(a.id)effective_emblem_id,a.visibility,a.level,a.xp,a.weekly_glory,a.max_members,count(m.user_id)::integer member_count from public.arena_alliances a left join public.arena_alliance_members m on m.alliance_id=a.id where a.visibility='open'and(trim(p_query)=''or a.name ilike'%'||trim(p_query)||'%'or a.tag ilike'%'||trim(p_query)||'%')group by a.id order by a.weekly_glory desc,count(m.user_id)desc limit least(greatest(p_limit,1),30))row_data$$;
create or replace function public.arena_get_alliance_hub()returns jsonb language plpgsql security definer set search_path=''as $$declare v_user uuid:=(select auth.uid());v_id uuid;v_result jsonb;begin if v_user is null then raise exception'authentication required';end if;select alliance_id into v_id from public.arena_alliance_members where user_id=v_user;if v_id is null then return null;end if;select jsonb_build_object('alliance',(select to_jsonb(x)from(select a.*,public.arena_alliance_effective_background(a.id)effective_background_id,public.arena_alliance_effective_emblem(a.id)effective_emblem_id,public.arena_alliance_has_pro(a.id)is_pro,count(allm.user_id)::integer member_count,m.role,m.contribution from public.arena_alliances a join public.arena_alliance_members m on m.alliance_id=a.id and m.user_id=v_user left join public.arena_alliance_members allm on allm.alliance_id=a.id where a.id=v_id group by a.id,m.role,m.contribution)x),'members',(select coalesce(jsonb_agg(to_jsonb(x)order by contribution desc,joined_at),'[]'::jsonb)from(select user_id,role,contribution,joined_at from public.arena_alliance_members where alliance_id=v_id limit 50)x),'activities',(select coalesce(jsonb_agg(to_jsonb(x)order by created_at desc),'[]'::jsonb)from(select id,kind,message,created_at from public.arena_alliance_activities where alliance_id=v_id order by created_at desc limit 30)x),'missions',(select coalesce(jsonb_agg(to_jsonb(x)order by ends_at),'[]'::jsonb)from(select id,title,description,target,progress,reward_label,ends_at from public.arena_alliance_missions where alliance_id=v_id and ends_at>now())x))into v_result;return v_result;end;$$;

revoke all on function public.arena_alliance_can_use_emblem(uuid,text),public.arena_alliance_effective_emblem(uuid),public.arena_get_alliance_emblems(),public.arena_purchase_alliance_emblem(text,text),public.arena_select_alliance_emblem(text) from public;
grant execute on function public.arena_get_alliance_emblems(),public.arena_purchase_alliance_emblem(text,text),public.arena_select_alliance_emblem(text) to authenticated;
commit;
