begin;
create table public.arena_alliance_shop_products(id text primary key check(id~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),name text not null,description text not null,image_path text not null,price_gems integer not null check(price_gems between 1 and 100000),rarity text not null check(rarity in('rare','epic','legendary')),contents jsonb not null check(jsonb_typeof(contents)='array'),active boolean not null default true,sort_order integer not null unique);
create table public.arena_alliance_shop_purchases(alliance_id uuid not null references public.arena_alliances(id)on delete cascade,product_id text not null references public.arena_alliance_shop_products(id),purchased_by uuid references public.profiles(id)on delete set null,price_gems integer not null,purchased_at timestamptz not null default now(),primary key(alliance_id,product_id));
insert into public.arena_alliance_shop_products values
('rota-dos-peregrinos','Rota dos Peregrinos','Porto de Társis e brasão da Arca para toda a Aliança.','/images/arena/alliance-backgrounds-v62/porto-de-tarsis.webp',700,'rare','[{"type":"background","id":"porto-de-tarsis"},{"type":"emblem","id":"arca-sobre-as-aguas"}]',true,1),
('fortaleza-de-neemias','Fortaleza de Neemias','Muralhas de Neemias e Trombetas de Jericó.','/images/arena/alliance-backgrounds-v62/muralhas-de-neemias.webp',900,'epic','[{"type":"background","id":"muralhas-de-neemias"},{"type":"emblem","id":"trombetas-de-jerico"}]',true,2),
('chama-do-carmelo','Chama do Carmelo','Monte Sinai e o brasão Fogo do Carmelo.','/images/arena/alliance-backgrounds-v62/monte-sinai.webp',1050,'legendary','[{"type":"background","id":"monte-sinai"},{"type":"emblem","id":"fogo-do-carmelo"}]',true,3),
('jardins-e-realeza','Jardins e Realeza','Jardim das Oliveiras, Palácio de Ester e Leão de Judá.','/images/arena/alliance-backgrounds-v62/palacio-de-ester.webp',1300,'legendary','[{"type":"background","id":"jardim-das-oliveiras"},{"type":"background","id":"palacio-de-ester"},{"type":"emblem","id":"leao-de-juda"}]',true,4),
('vigias-do-reino','Vigias do Reino','Torre de Vigia, Refúgio do Jordão e brasão da Arca.','/images/arena/alliance-backgrounds-v62/torre-de-vigia.webp',1350,'legendary','[{"type":"background","id":"torre-de-vigia"},{"type":"background","id":"refugio-do-jordao"},{"type":"emblem","id":"arca-sobre-as-aguas"}]',true,5);
alter table public.arena_alliance_shop_products enable row level security;alter table public.arena_alliance_shop_products force row level security;alter table public.arena_alliance_shop_purchases enable row level security;alter table public.arena_alliance_shop_purchases force row level security;revoke all on public.arena_alliance_shop_products,public.arena_alliance_shop_purchases from anon,authenticated;
create or replace function public.arena_get_alliance_shop()returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_alliance uuid;v_role text;begin select alliance_id,role into v_alliance,v_role from public.arena_alliance_members where user_id=v_user;if v_alliance is null then raise exception'alliance required';end if;return jsonb_build_object('balance',coalesce((select gems from public.arena_alliance_treasuries where alliance_id=v_alliance),0),'can_buy',v_role in('founder','elder'),'products',(select jsonb_agg(jsonb_build_object('id',p.id,'name',p.name,'description',p.description,'image',p.image_path,'price',p.price_gems,'rarity',p.rarity,'contents',p.contents,'owned',exists(select 1 from public.arena_alliance_shop_purchases x where x.alliance_id=v_alliance and x.product_id=p.id))order by p.sort_order)from public.arena_alliance_shop_products p where p.active));end;$$;
create or replace function public.arena_purchase_alliance_shop_product(p_product_id text,p_idempotency_key text)returns jsonb language plpgsql security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_alliance uuid;v_role text;v_product public.arena_alliance_shop_products%rowtype;v_treasury public.arena_alliance_treasuries%rowtype;v_item jsonb;begin select alliance_id,role into v_alliance,v_role from public.arena_alliance_members where user_id=v_user;if v_alliance is null or v_role not in('founder','elder')or length(coalesce(p_idempotency_key,''))<16 then raise exception'alliance manager required';end if;select*into v_product from public.arena_alliance_shop_products where id=p_product_id and active;if not found then raise exception'product unavailable';end if;if exists(select 1 from public.arena_alliance_shop_purchases where alliance_id=v_alliance and product_id=v_product.id)then return jsonb_build_object('purchased',true,'already_owned',true);end if;if exists(select 1 from public.arena_alliance_treasury_ledger where idempotency_key=p_idempotency_key)then return jsonb_build_object('purchased',true,'replayed',true);end if;insert into public.arena_alliance_treasuries(alliance_id)values(v_alliance)on conflict do nothing;select*into v_treasury from public.arena_alliance_treasuries where alliance_id=v_alliance for update;if v_treasury.gems<v_product.price_gems then raise exception'insufficient treasury';end if;update public.arena_alliance_treasuries set gems=gems-v_product.price_gems,updated_at=now()where alliance_id=v_alliance;insert into public.arena_alliance_shop_purchases values(v_alliance,v_product.id,v_user,v_product.price_gems,now());for v_item in select*from jsonb_array_elements(v_product.contents)loop if v_item->>'type'='background'then insert into public.arena_alliance_background_unlocks(alliance_id,background_id,purchased_by,gem_price)values(v_alliance,v_item->>'id',v_user,1)on conflict do nothing;elsif v_item->>'type'='emblem'then insert into public.arena_alliance_emblem_unlocks(alliance_id,emblem_id,purchased_by,gem_price)values(v_alliance,v_item->>'id',v_user,1)on conflict do nothing;else raise exception'invalid product contents';end if;end loop;insert into public.arena_alliance_treasury_ledger(alliance_id,actor_id,amount,entry_type,reference_id,idempotency_key)values(v_alliance,v_user,-v_product.price_gems,'purchase',v_product.id,p_idempotency_key);insert into public.arena_alliance_activities(alliance_id,actor_id,kind,message)values(v_alliance,v_user,'system','A Aliança desbloqueou o pacote '||v_product.name||'.');return jsonb_build_object('purchased',true,'product_id',v_product.id,'balance',v_treasury.gems-v_product.price_gems);end;$$;
revoke all on function public.arena_get_alliance_shop(),public.arena_purchase_alliance_shop_product(text,text)from public;grant execute on function public.arena_get_alliance_shop(),public.arena_purchase_alliance_shop_product(text,text)to authenticated;
commit;
