begin;
create table public.arena_refund_requests(
 id uuid primary key default gen_random_uuid(),request_code text not null unique default('ARR-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10))),
 user_id uuid not null references auth.users(id) on delete cascade,receipt_id uuid not null references public.arena_purchase_receipts(id),
 reason text not null check(reason in('delivery_problem','duplicate_purchase','technical_problem','withdrawal_request','other')),
 details text not null check(length(details) between 10 and 800),status text not null default'under_review' check(status in('under_review','approved','rejected','completed')),
 admin_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,receipt_id)
);
create trigger arena_refund_requests_set_updated_at before update on public.arena_refund_requests for each row execute function public.set_updated_at();
alter table public.arena_refund_requests enable row level security;alter table public.arena_refund_requests force row level security;
create policy "arena_refund_requests_read_own" on public.arena_refund_requests for select to authenticated using((select auth.uid())=user_id);
revoke all on public.arena_refund_requests from anon,authenticated;grant select on public.arena_refund_requests to authenticated;
create or replace function public.arena_request_refund(p_receipt_id uuid,p_reason text,p_details text) returns jsonb language plpgsql security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_receipt public.arena_purchase_receipts%rowtype;v_request public.arena_refund_requests%rowtype;begin if v_user is null then raise exception 'authentication required';end if;select * into v_receipt from public.arena_purchase_receipts where id=p_receipt_id and user_id=v_user and status='paid';if not found then raise exception 'paid receipt required';end if;if p_reason not in('delivery_problem','duplicate_purchase','technical_problem','withdrawal_request','other') or length(trim(p_details)) not between 10 and 800 then raise exception 'invalid request';end if;insert into public.arena_refund_requests(user_id,receipt_id,reason,details) values(v_user,p_receipt_id,p_reason,trim(p_details)) returning * into v_request;return jsonb_build_object('id',v_request.id,'request_code',v_request.request_code,'status',v_request.status);exception when unique_violation then raise exception 'request already exists';end;$$;
create or replace function public.arena_admin_list_refund_requests() returns jsonb language plpgsql security definer set search_path='' as $$declare v_user uuid:=(select auth.uid());v_result jsonb;begin if v_user is null or not exists(select 1 from public.arena_admins where user_id=v_user) then raise exception 'administrator required';end if;select coalesce(jsonb_agg(jsonb_build_object('request_code',r.request_code,'receipt_id',r.receipt_id,'product_id',p.product_id,'reason',r.reason,'status',r.status,'amount_minor',p.amount_minor,'created_at',r.created_at) order by r.created_at desc),'[]'::jsonb) into v_result from public.arena_refund_requests r join public.arena_purchase_receipts p on p.id=r.receipt_id;return v_result;end;$$;
revoke all on function public.arena_request_refund(uuid,text,text),public.arena_admin_list_refund_requests() from public;grant execute on function public.arena_request_refund(uuid,text,text),public.arena_admin_list_refund_requests() to authenticated;
commit;
