begin;

-- V196: pesquisas longas conectam conhecimento, tropas, missão e navegação.
insert into public.apostolic_research_catalog(code,branch,name,description,tier,prerequisites,academy_level,base_costs,duration_seconds,effect,sort_order)values
('navigation_basics','navigation','Leitura das Águas','Desbloqueia navegação costeira segura.',1,'{}',1,'{"cedar":90,"oil":50,"gold":80}',600,'{"unlock":"coastal_vessels"}',9),
('merchant_hulls','navigation','Cascos Mercantis','Desbloqueia navios dedicados ao transporte.',2,'{navigation_basics}',3,'{"cedar":180,"stone":80,"oil":90,"gold":140}',1200,'{"unlock":"merchant_vessels"}',10),
('cargo_logistics','logistics','Logística de Cargas','Amplia a organização das frotas mercantis.',3,'{merchant_hulls,caravan_routes}',5,'{"cedar":280,"stone":150,"oil":160,"gold":240}',2400,'{"unlock":"advanced_cargo"}',11),
('coastal_watch','defense','Vigilância Costeira','Forma tripulações para patrulhar portos.',1,'{watchtowers}',2,'{"cedar":130,"stone":110,"oil":70,"gold":110}',900,'{"unlock":"watch_boats"}',12),
('shield_formation','defense','Formação de Escudos','Desbloqueia defensores organizados.',2,'{watchtowers}',3,'{"wheat":160,"cedar":120,"stone":150,"gold":140}',1500,'{"unlock":"spearmen"}',13),
('composite_bows','defense','Arcos Reforçados','Aprimora a defesa de longo alcance.',3,'{shield_formation,cedar_craft}',5,'{"cedar":260,"stone":130,"oil":110,"gold":220}',2700,'{"unlock":"archers"}',14),
('naval_defense','defense','Defesa Naval','Desbloqueia navios protetores sem poder comprado.',3,'{coastal_watch,stone_masonry}',5,'{"cedar":320,"stone":210,"oil":180,"gold":260}',3000,'{"unlock":"defense_vessels"}',15),
('mission_routes','mission','Rotas Missionárias','Prepara equipes para servir regiões distantes.',2,'{caravan_routes,navigation_basics}',4,'{"wheat":190,"cedar":160,"oil":130,"gold":180}',2100,'{"unlock":"mission_routes"}',16);

-- V197: requisitos científicos são aplicados no banco, não apenas na interface.
alter table public.apostolic_unit_catalog add column required_research_code text references public.apostolic_research_catalog(code);
update public.apostolic_unit_catalog set required_research_code=case code when'watchman'then'watchtowers'when'slinger'then'watchtowers'when'spearman'then'shield_formation'when'archer'then'composite_bows'end;
alter table public.apostolic_unit_catalog alter column required_research_code set not null;
alter table public.apostolic_building_action_catalog add column required_research_code text references public.apostolic_research_catalog(code);
update public.apostolic_building_action_catalog set required_research_code=case when building='academy'then'fair_measures'when building='embassy'then'mission_routes'when building='shipyard'then'coastal_watch'when building='barracks'then'shield_formation'when building='wall'then'watchtowers'end;

create or replace function public.apostolic_require_connected_research()returns trigger language plpgsql security invoker set search_path=''as $$
declare required_code text;
begin
 if tg_table_name='apostolic_training_queue'then select required_research_code into required_code from public.apostolic_unit_catalog where code=new.unit_code;
 else select required_research_code into required_code from public.apostolic_building_action_catalog where building=new.building and action=new.action;end if;
 if required_code is not null and not exists(select 1 from public.apostolic_city_research where city_id=new.city_id and research_code=required_code)then raise exception'research required: %',required_code;end if;
 return new;
end;$$;
create trigger apostolic_training_research_guard before insert on public.apostolic_training_queue for each row execute function public.apostolic_require_connected_research();
create trigger apostolic_purpose_research_guard before insert on public.apostolic_building_action_queue for each row execute function public.apostolic_require_connected_research();

-- V198: navios mercantis e defensivos possuem capacidade, pesquisa e custo próprios.
create table public.apostolic_vessel_catalog(code text primary key,name text not null,description text not null,role text not null check(role in('merchant','defense')),cargo_capacity integer not null default 0 check(cargo_capacity>=0),attack smallint not null default 0 check(attack>=0),defense smallint not null default 0 check(defense>=0),space smallint not null check(space between 1 and 10),shipyard_level smallint not null check(shipyard_level between 1 and 40),required_research_code text not null references public.apostolic_research_catalog(code),duration_seconds integer not null check(duration_seconds between 60 and 604800),costs jsonb not null check(jsonb_typeof(costs)='object'and not(costs?'gems')),sort_order smallint not null unique);
insert into public.apostolic_vessel_catalog values
('coastal_barge','Barca Costeira','Transporta cargas entre portos próximos.','merchant',350,0,18,2,1,'navigation_basics',900,'{"cedar":140,"oil":55,"gold":70}',1),
('covenant_merchant','Mercante da Aliança','Navio mercantil de longo curso.','merchant',1100,0,32,4,3,'merchant_hulls',2400,'{"cedar":320,"stone":90,"oil":130,"gold":180}',2),
('watch_boat','Barco de Vigia','Embarcação ágil de patrulha costeira.','defense',80,28,42,3,2,'coastal_watch',1800,'{"cedar":220,"stone":80,"oil":110,"gold":120}',3),
('cedar_guardian','Guardião de Cedro','Navio resistente para defender rotas e cidades.','defense',120,55,85,6,5,'naval_defense',4200,'{"cedar":480,"stone":240,"oil":210,"gold":300}',4);
create table public.apostolic_city_fleet(city_id uuid not null references public.apostolic_cities(id)on delete cascade,vessel_code text not null references public.apostolic_vessel_catalog(code),ready integer not null default 0 check(ready>=0),updated_at timestamptz not null default clock_timestamp(),primary key(city_id,vessel_code));
insert into public.apostolic_city_fleet(city_id,vessel_code)select c.id,v.code from public.apostolic_cities c cross join public.apostolic_vessel_catalog v on conflict do nothing;
create or replace function public.apostolic_create_city_fleet()returns trigger language plpgsql security invoker set search_path=''as $$begin insert into public.apostolic_city_fleet(city_id,vessel_code)select new.id,code from public.apostolic_vessel_catalog on conflict do nothing;return new;end;$$;
create trigger apostolic_city_fleet_after_insert after insert on public.apostolic_cities for each row execute function public.apostolic_create_city_fleet();
create table public.apostolic_vessel_queue(id uuid primary key default gen_random_uuid(),city_id uuid not null references public.apostolic_cities(id)on delete cascade,vessel_code text not null references public.apostolic_vessel_catalog(code),quantity smallint not null check(quantity between 1 and 10),costs jsonb not null,started_at timestamptz not null default clock_timestamp(),finishes_at timestamptz not null,status text not null default'building'check(status in('building','completed','cancelled')),idempotency_key uuid not null,completed_at timestamptz,unique(city_id,idempotency_key));
create unique index apostolic_vessel_one_active_idx on public.apostolic_vessel_queue(city_id)where status='building';
create index apostolic_vessel_due_idx on public.apostolic_vessel_queue(finishes_at,city_id)where status='building';
alter table public.apostolic_vessel_catalog enable row level security;alter table public.apostolic_vessel_catalog force row level security;alter table public.apostolic_city_fleet enable row level security;alter table public.apostolic_city_fleet force row level security;alter table public.apostolic_vessel_queue enable row level security;alter table public.apostolic_vessel_queue force row level security;
revoke all on public.apostolic_vessel_catalog,public.apostolic_city_fleet,public.apostolic_vessel_queue from anon,authenticated;

-- V199-V200: construção naval temporal, idempotente e sem moeda premium.
create or replace function public.apostolic_get_fleet_center()returns jsonb language sql stable security definer set search_path=''as $$
with own as(select id from public.apostolic_cities where owner_id=(select auth.uid())),yard as(select level from public.apostolic_city_buildings where city_id=(select id from own)and building='shipyard')select case when not exists(select 1 from own)then null else jsonb_build_object('shipyard_level',coalesce((select level from yard),0),'capacity',coalesce((select level from yard),0)*12,'used_space',(select coalesce(sum(f.ready*v.space),0)from public.apostolic_city_fleet f join public.apostolic_vessel_catalog v on v.code=f.vessel_code where f.city_id=(select id from own)),'merchant_capacity',(select coalesce(sum(f.ready*v.cargo_capacity),0)from public.apostolic_city_fleet f join public.apostolic_vessel_catalog v on v.code=f.vessel_code where f.city_id=(select id from own)and v.role='merchant'),'defense_power',(select coalesce(sum(f.ready*(v.attack+v.defense)),0)from public.apostolic_city_fleet f join public.apostolic_vessel_catalog v on v.code=f.vessel_code where f.city_id=(select id from own)and v.role='defense'),'queue',(select to_jsonb(q)from(select id,vessel_code,quantity,started_at,finishes_at from public.apostolic_vessel_queue where city_id=(select id from own)and status='building'limit 1)q),'vessels',(select jsonb_agg(jsonb_build_object('code',v.code,'name',v.name,'description',v.description,'role',v.role,'cargo_capacity',v.cargo_capacity,'attack',v.attack,'defense',v.defense,'space',v.space,'shipyard_level',v.shipyard_level,'research_code',v.required_research_code,'research_name',r.name,'research_unlocked',exists(select 1 from public.apostolic_city_research x where x.city_id=(select id from own)and x.research_code=v.required_research_code),'duration_seconds',v.duration_seconds,'costs',v.costs,'ready',coalesce(f.ready,0))order by v.sort_order)from public.apostolic_vessel_catalog v join public.apostolic_research_catalog r on r.code=v.required_research_code left join public.apostolic_city_fleet f on f.city_id=(select id from own)and f.vessel_code=v.code))end$$;
create or replace function public.apostolic_sync_fleet_center()returns jsonb language plpgsql security definer set search_path=''as $$declare uid uuid:=(select auth.uid());cid uuid;q public.apostolic_vessel_queue%rowtype;begin if uid is null then raise exception'authentication required';end if;select id into cid from public.apostolic_cities where owner_id=uid for update;if cid is null then return null;end if;select*into q from public.apostolic_vessel_queue where city_id=cid and status='building'and finishes_at<=clock_timestamp()order by finishes_at for update limit 1;if found then update public.apostolic_city_fleet set ready=ready+q.quantity,updated_at=clock_timestamp()where city_id=cid and vessel_code=q.vessel_code;update public.apostolic_vessel_queue set status='completed',completed_at=clock_timestamp()where id=q.id;end if;return public.apostolic_get_fleet_center();end;$$;
create or replace function public.apostolic_start_vessel_construction(p_vessel_code text,p_quantity integer,p_idempotency_key uuid)returns jsonb language plpgsql security definer set search_path=''as $$declare uid uuid:=(select auth.uid());cid uuid;v public.apostolic_vessel_catalog%rowtype;yard integer;used integer;total jsonb;r record;cost bigint;begin if uid is null or p_idempotency_key is null then raise exception'authentication required';end if;if p_quantity not between 1 and 10 then raise exception'invalid quantity';end if;select id into cid from public.apostolic_cities where owner_id=uid for update;if cid is null then raise exception'city not found';end if;if exists(select 1 from public.apostolic_vessel_queue where city_id=cid and idempotency_key=p_idempotency_key)then return public.apostolic_get_fleet_center();end if;perform public.apostolic_sync_fleet_center();if exists(select 1 from public.apostolic_vessel_queue where city_id=cid and status='building')then raise exception'shipyard queue occupied';end if;select*into v from public.apostolic_vessel_catalog where code=p_vessel_code;if not found then raise exception'vessel unavailable';end if;select level into yard from public.apostolic_city_buildings where city_id=cid and building='shipyard'and state='ready'for update;if coalesce(yard,0)<v.shipyard_level then raise exception'shipyard level required';end if;if not exists(select 1 from public.apostolic_city_research where city_id=cid and research_code=v.required_research_code)then raise exception'research required: %',v.required_research_code;end if;select coalesce(sum(f.ready*c.space),0)into used from public.apostolic_city_fleet f join public.apostolic_vessel_catalog c on c.code=f.vessel_code where f.city_id=cid;if used+p_quantity*v.space>yard*12 then raise exception'fleet capacity exceeded';end if;select jsonb_object_agg(key,(value::text)::bigint*p_quantity)into total from jsonb_each(v.costs);for r in select key,value from jsonb_each_text(total)loop cost:=r.value::bigint;if not exists(select 1 from public.apostolic_city_resources where city_id=cid and resource=r.key and amount>=cost)then raise exception'insufficient resource: %',r.key;end if;end loop;for r in select key,value from jsonb_each_text(total)loop cost:=r.value::bigint;update public.apostolic_city_resources set amount=amount-cost where city_id=cid and resource=r.key;insert into public.apostolic_resource_ledger(city_id,resource,delta,balance_after,reason,idempotency_key)select cid,r.key,-cost,amount,'vessel:'||p_vessel_code,p_idempotency_key from public.apostolic_city_resources where city_id=cid and resource=r.key;end loop;insert into public.apostolic_vessel_queue(city_id,vessel_code,quantity,costs,finishes_at,idempotency_key)values(cid,p_vessel_code,p_quantity,total,clock_timestamp()+make_interval(secs=>v.duration_seconds*p_quantity),p_idempotency_key);return public.apostolic_get_fleet_center();end;$$;
revoke all on function public.apostolic_get_fleet_center(),public.apostolic_sync_fleet_center(),public.apostolic_start_vessel_construction(text,integer,uuid),public.apostolic_create_city_fleet(),public.apostolic_require_connected_research()from public,anon,authenticated;
grant execute on function public.apostolic_get_fleet_center(),public.apostolic_sync_fleet_center(),public.apostolic_start_vessel_construction(text,integer,uuid)to authenticated;
commit;
